import type { Language } from "@/lib/translations";

export type InquiryValue = string | string[] | boolean | null;
export type InquiryAnswers = Record<string, InquiryValue>;

export type InquiryOption = {
  value: string;
  label: string;
  description?: string;
};

export type InquiryFieldType =
  | "text"
  | "email"
  | "phone"
  | "url"
  | "textarea"
  | "single_choice"
  | "multiple_choice"
  | "date"
  | "ranking"
  | "consent";

export type InquiryField = {
  key: string;
  label: string;
  type: InquiryFieldType;
  required?: boolean;
  placeholder?: string;
  description?: string;
  options?: InquiryOption[];
  showWhen?: (answers: InquiryAnswers) => boolean;
};

export type InquiryStep = {
  key: string;
  title: string;
  eyebrow: string;
  description: string;
  projectTypes?: string[];
  fields: InquiryField[];
};

export type InquiryUiCopy = {
  seoTitle: string;
  seoDescription: string;
  badge: string;
  title: string;
  subtitle: string;
  introTitle: string;
  introText: string;
  start: string;
  next: string;
  back: string;
  submit: string;
  sending: string;
  required: string;
  progress: string;
  step: string;
  successTitle: string;
  successText: string;
  errorTitle: string;
  noEndpoint: string;
  invalidEmail: string;
  invalidUrl: string;
  invalidDate: string;
  invalidProtocol: string;
  protectionFailed: string;
  tooFast: string;
  rateLimited: string;
  wrongChallenge: string;
  challengeTitle: string;
  challengePlaceholder: string;
  confirmationSubject: string;
  confirmationIntro: string;
  adminSubject: string;
};

export const PROJECT_INQUIRY_PATH = "/projektni-upitnik";
export const PROJECT_INQUIRY_ENDPOINT_ENV = "VITE_PROJECT_INQUIRY_ENDPOINT";

export const projectInquiryCopy: Record<Language, InquiryUiCopy> = {
  sr: {
    seoTitle: "Projektni upitnik za web sajt, web shop ili aplikaciju | Wizionar",
    seoDescription:
      "Popunite profesionalni projektni upitnik za web sajt, web shop, booking sistem, aplikaciju ili redizajn. Wizionar analizira odgovore i predlaže naredne korake.",
    badge: "Project Discovery",
    title: "Projektni upitnik za web sajt ili aplikaciju",
    subtitle:
      "Kroz nekoliko fokusiranih koraka prikupimo poslovne ciljeve, funkcionalnosti, budžet, rokove i tehničke zahtjeve, da vam možemo pripremiti smislen prijedlog.",
    introTitle: "Prije nego počnemo",
    introText:
      "Upitnik traje oko 10-20 minuta. Ne morate znati sve odgovore; gdje niste sigurni, izaberite opciju koja to kaže.",
    start: "Započni upitnik",
    next: "Dalje",
    back: "Nazad",
    submit: "Pošalji upitnik",
    sending: "Slanje...",
    required: "Ovo polje je obavezno.",
    progress: "Popunjeno",
    step: "Korak",
    successTitle: "Hvala na poslanom upitniku.",
    successText:
      "Vaši odgovori su zaprimljeni. Analiziraćemo tip projekta, obim funkcionalnosti, kompleksnost, rokove i javiti se sa prijedlogom narednih koraka.",
    errorTitle: "Nismo uspjeli poslati upitnik.",
    noEndpoint:
      "Email endpoint još nije podešen, pa smo otvorili pripremljen email sa svim odgovorima.",
    invalidEmail: "Unesite ispravnu email adresu.",
    invalidUrl: "Unesite ispravan link.",
    invalidDate: "Unesite datum u formatu dd.mm.gggg.",
    invalidProtocol: "Link mora početi sa http ili https.",
    protectionFailed: "Zaštitna provjera nije prošla.",
    tooFast: "Molimo sačekajte nekoliko sekundi prije slanja.",
    rateLimited: "Upitnik je već poslan nedavno. Pokušajte ponovo za minut.",
    wrongChallenge: "Rezultat matematičke provjere nije tačan.",
    challengeTitle: "Provjera prije slanja",
    challengePlaceholder: "Rezultat",
    confirmationSubject: "Kopija vašeg projektnog upitnika - Wizionar",
    confirmationIntro:
      "Hvala što ste popunili projektni upitnik. U nastavku je kopija odgovora koje ste poslali. Javićemo vam se sa narednim koracima.",
    adminSubject: "Novi projektni upitnik - Wizionar",
  },
  en: {
    seoTitle: "Project inquiry for websites, shops and applications | Wizionar",
    seoDescription:
      "Complete a professional project inquiry for a website, online shop, booking system, app or redesign. Wizionar reviews the answers and proposes next steps.",
    badge: "Project Discovery",
    title: "Project inquiry for a website or application",
    subtitle:
      "A focused multi-step form helps us collect goals, features, budget, timeline and technical context so we can prepare a meaningful proposal.",
    introTitle: "Before we start",
    introText:
      "The form takes about 10-20 minutes. You do not need every answer; choose an unsure option where needed.",
    start: "Start inquiry",
    next: "Next",
    back: "Back",
    submit: "Submit inquiry",
    sending: "Sending...",
    required: "This field is required.",
    progress: "Completed",
    step: "Step",
    successTitle: "Thank you for the submitted inquiry.",
    successText:
      "Your answers have been received. We will review the project type, scope, complexity and timeline and contact you with next steps.",
    errorTitle: "We could not submit the inquiry.",
    noEndpoint:
      "The email endpoint is not configured yet, so we opened a prepared email with all answers.",
    invalidEmail: "Enter a valid email address.",
    invalidUrl: "Enter a valid URL.",
    invalidDate: "Enter the date in dd.mm.yyyy format.",
    invalidProtocol: "The URL must start with http or https.",
    protectionFailed: "The protection check failed.",
    tooFast: "Please wait a few seconds before submitting.",
    rateLimited: "The inquiry was submitted recently. Please try again in a minute.",
    wrongChallenge: "The math check result is not correct.",
    challengeTitle: "Check before sending",
    challengePlaceholder: "Result",
    confirmationSubject: "Copy of your project inquiry - Wizionar",
    confirmationIntro:
      "Thank you for completing the project inquiry. Below is a copy of the answers you submitted. We will contact you with next steps.",
    adminSubject: "New project inquiry - Wizionar",
  },
  de: {
    seoTitle: "Projektfragebogen für Websites, Shops und Anwendungen | Wizionar",
    seoDescription:
      "Füllen Sie einen professionellen Projektfragebogen für Website, Online-Shop, Buchungssystem, App oder Redesign aus. Wizionar prüft die Antworten und schlägt nächste Schritte vor.",
    badge: "Project Discovery",
    title: "Projektfragebogen für Website oder Anwendung",
    subtitle:
      "Ein fokussiertes mehrstufiges Formular erfasst Ziele, Funktionen, Budget, Zeitplan und technische Rahmenbedingungen für ein sinnvolles Angebot.",
    introTitle: "Bevor wir starten",
    introText:
      "Das Formular dauert etwa 10-20 Minuten. Sie müssen nicht alles wissen; wählen Sie bei Bedarf eine Unsicher-Option.",
    start: "Fragebogen starten",
    next: "Weiter",
    back: "Zurück",
    submit: "Fragebogen senden",
    sending: "Senden...",
    required: "Dieses Feld ist erforderlich.",
    progress: "Ausgefüllt",
    step: "Schritt",
    successTitle: "Vielen Dank für den gesendeten Fragebogen.",
    successText:
      "Ihre Antworten wurden empfangen. Wir prüfen Projekttyp, Umfang, Komplexität und Zeitplan und melden uns mit den nächsten Schritten.",
    errorTitle: "Der Fragebogen konnte nicht gesendet werden.",
    noEndpoint:
      "Der Email-Endpunkt ist noch nicht konfiguriert, daher wurde eine vorbereitete Email mit allen Antworten geöffnet.",
    invalidEmail: "Geben Sie eine gültige Email-Adresse ein.",
    invalidUrl: "Geben Sie einen gültigen Link ein.",
    invalidDate: "Geben Sie das Datum im Format tt.mm.jjjj ein.",
    invalidProtocol: "Der Link muss mit http oder https beginnen.",
    protectionFailed: "Die Schutzprüfung ist fehlgeschlagen.",
    tooFast: "Bitte warten Sie einige Sekunden vor dem Absenden.",
    rateLimited: "Der Fragebogen wurde kürzlich gesendet. Bitte versuchen Sie es in einer Minute erneut.",
    wrongChallenge: "Das Ergebnis der Mathe-Prüfung ist nicht korrekt.",
    challengeTitle: "Prüfung vor dem Absenden",
    challengePlaceholder: "Ergebnis",
    confirmationSubject: "Kopie Ihres Projektfragebogens - Wizionar",
    confirmationIntro:
      "Vielen Dank für das Ausfüllen des Projektfragebogens. Unten finden Sie eine Kopie Ihrer gesendeten Antworten. Wir melden uns mit den nächsten Schritten.",
    adminSubject: "Neuer Projektfragebogen - Wizionar",
  },
  it: {
    seoTitle: "Questionario progetto per siti, shop e applicazioni | Wizionar",
    seoDescription:
      "Compila un questionario professionale per sito web, shop online, sistema booking, app o redesign. Wizionar analizza le risposte e propone i prossimi passi.",
    badge: "Project Discovery",
    title: "Questionario progetto per sito web o applicazione",
    subtitle:
      "Un modulo multi-step raccoglie obiettivi, funzionalità, budget, tempi e contesto tecnico per preparare una proposta concreta.",
    introTitle: "Prima di iniziare",
    introText:
      "Il questionario richiede circa 10-20 minuti. Non serve sapere tutto; scegli un'opzione incerta dove necessario.",
    start: "Inizia questionario",
    next: "Avanti",
    back: "Indietro",
    submit: "Invia questionario",
    sending: "Invio...",
    required: "Questo campo è obbligatorio.",
    progress: "Completato",
    step: "Passo",
    successTitle: "Grazie per il questionario inviato.",
    successText:
      "Le tue risposte sono state ricevute. Analizzeremo tipo di progetto, ambito, complessità e tempi e ti contatteremo con i prossimi passi.",
    errorTitle: "Non siamo riusciti a inviare il questionario.",
    noEndpoint:
      "L'endpoint email non è ancora configurato, quindi abbiamo aperto una email preparata con tutte le risposte.",
    invalidEmail: "Inserisci un indirizzo email valido.",
    invalidUrl: "Inserisci un link valido.",
    invalidDate: "Inserisci la data nel formato gg.mm.aaaa.",
    invalidProtocol: "Il link deve iniziare con http o https.",
    protectionFailed: "Il controllo di protezione non è riuscito.",
    tooFast: "Attendi qualche secondo prima di inviare.",
    rateLimited: "Il questionario è stato inviato di recente. Riprova tra un minuto.",
    wrongChallenge: "Il risultato del controllo matematico non è corretto.",
    challengeTitle: "Controllo prima dell'invio",
    challengePlaceholder: "Risultato",
    confirmationSubject: "Copia del tuo questionario progetto - Wizionar",
    confirmationIntro:
      "Grazie per aver compilato il questionario progetto. Di seguito trovi una copia delle risposte inviate. Ti contatteremo con i prossimi passi.",
    adminSubject: "Nuovo questionario progetto - Wizionar",
  },
};

const yesNoUnsure: InquiryOption[] = [
  { value: "yes", label: "Da" },
  { value: "no", label: "Ne" },
  { value: "not_sure", label: "Nisam siguran/sigurna" },
];

const projectTypeOptions: InquiryOption[] = [
  {
    value: "presentation_website",
    label: "Prezentacioni web sajt",
    description: "Predstavljanje firme, usluga, tima, referenci, lokacije i kontakta.",
  },
  {
    value: "ecommerce",
    label: "Web shop / online prodavnica",
    description: "Online prodaja proizvoda, korpa, narudžbe, plaćanje i administracija.",
  },
  {
    value: "web_application",
    label: "Web aplikacija / platforma",
    description: "Napredni sistem sa korisnicima, dashboardima, bazom i poslovnom logikom.",
  },
  {
    value: "booking_system",
    label: "Booking / rezervacijski sistem",
    description: "Rezervacija termina, usluga, vozila, smještaja, konsultacija ili resursa.",
  },
  {
    value: "landing_page",
    label: "Landing page",
    description: "Jedna prodajna stranica fokusirana na kampanju, proizvod ili prijave.",
  },
  {
    value: "redesign",
    label: "Redizajn postojećeg sajta ili aplikacije",
    description: "Bolji dizajn, performanse, SEO, funkcionalnosti ili korisničko iskustvo.",
  },
  {
    value: "not_sure",
    label: "Nisam siguran/sigurna",
    description: "Kroz odgovore ćemo zajedno procijeniti najbolji tip rješenja.",
  },
];

export const projectInquirySteps: InquiryStep[] = [
  {
    key: "contact",
    eyebrow: "Osnovni podaci",
    title: "Ko nam se javlja?",
    description: "Podaci potrebni da vas možemo kontaktirati i razumjeti kontekst poslovanja.",
    fields: [
      { key: "full_name", label: "Ime i prezime", type: "text", required: true },
      { key: "company_name", label: "Naziv firme / projekta", type: "text" },
      { key: "email", label: "Email adresa", type: "email", required: true },
      { key: "phone", label: "Telefon", type: "phone" },
      { key: "location", label: "Država / grad", type: "text" },
      {
        key: "business_description",
        label: "Čime se bavite?",
        type: "textarea",
        required: true,
        placeholder: "Ukratko opišite vašu firmu, usluge, proizvode ili ideju.",
      },
    ],
  },
  {
    key: "classification",
    eyebrow: "Klasifikacija",
    title: "Kakav projekat želite izraditi?",
    description: "Ovaj odgovor određuje koja dodatna pitanja ćemo prikazati u nastavku.",
    fields: [
      {
        key: "project_type",
        label: "Tip projekta",
        type: "single_choice",
        required: true,
        options: projectTypeOptions,
      },
      {
        key: "idea_if_unsure",
        label: "Ako niste sigurni, opišite ideju svojim riječima",
        type: "textarea",
        required: true,
        showWhen: (answers) => answers.project_type === "not_sure",
      },
    ],
  },
  {
    key: "goals",
    eyebrow: "Ciljevi",
    title: "Šta projekat treba postići?",
    description: "Birajte više odgovora ako projekat ima više poslovnih ciljeva.",
    fields: [
      {
        key: "main_goals",
        label: "Glavni cilj projekta",
        type: "multiple_choice",
        required: true,
        options: [
          "Predstavljanje firme ili usluga",
          "Povećanje broja upita",
          "Online prodaja proizvoda",
          "Online prodaja usluga",
          "Automatizacija poslovnog procesa",
          "Rezervacija termina",
          "Upravljanje korisnicima",
          "Edukacija korisnika",
          "Kreiranje zajednice / community sistema",
          "Interni poslovni sistem",
          "SaaS aplikacija",
          "Marketplace/platforma",
          "Bolji SEO i Google vidljivost",
          "Bolji dizajn i korisničko iskustvo",
          "Drugo",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "other_goal",
        label: "Opišite drugi cilj",
        type: "textarea",
        required: true,
        showWhen: (answers) => Array.isArray(answers.main_goals) && answers.main_goals.includes("Drugo"),
      },
      {
        key: "project_description",
        label: "Šta korisnik treba moći uraditi na sajtu ili aplikaciji?",
        type: "textarea",
        required: true,
        placeholder:
          "Primjer: pregledati usluge, poslati upit, kupiti proizvod, rezervisati termin, prijaviti se ili koristiti dashboard.",
      },
    ],
  },
  {
    key: "current_state",
    eyebrow: "Postojeće stanje",
    title: "Da li već imate digitalno rješenje?",
    description: "Ako već imate web sajt, shop ili aplikaciju, korisno je znati šta radi dobro, a šta treba popraviti.",
    fields: [
      {
        key: "existing_solution_status",
        label: "Da li trenutno imate web sajt, web shop ili aplikaciju?",
        type: "single_choice",
        required: true,
        options: ["Da", "Ne", "U izradi je", "Nisam siguran/sigurna"].map((label) => ({ value: label, label })),
      },
      {
        key: "existing_solution_url",
        label: "Link postojećeg sajta / aplikacije",
        type: "url",
        showWhen: (answers) => ["Da", "U izradi je"].includes(String(answers.existing_solution_status || "")),
      },
      {
        key: "existing_solution_pain_points",
        label: "Šta vam najviše smeta na postojećem rješenju?",
        type: "multiple_choice",
        showWhen: (answers) => ["Da", "U izradi je"].includes(String(answers.existing_solution_status || "")),
        options: [
          "Zastarjeli dizajn",
          "Spor sajt",
          "Loša mobilna verzija",
          "Loša Google vidljivost",
          "Teško uređivanje sadržaja",
          "Nema admin panel",
          "Nema online plaćanje",
          "Loše korisničko iskustvo",
          "Nedostaju funkcionalnosti",
          "Tehnički problemi",
          "Sigurnosni problemi",
          "Ne znam",
          "Drugo",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "existing_solution_other_problem",
        label: "Opišite problem",
        type: "textarea",
        showWhen: (answers) =>
          Array.isArray(answers.existing_solution_pain_points) &&
          answers.existing_solution_pain_points.includes("Drugo"),
      },
    ],
  },
  {
    key: "technical_base",
    eyebrow: "Domen i hosting",
    title: "Tehnička osnova projekta",
    description: "Domen je internet adresa, a hosting je prostor/server na kojem se nalazi web sajt ili aplikacija.",
    fields: [
      {
        key: "domain_status",
        label: "Da li imate domen?",
        type: "single_choice",
        required: true,
        options: ["Da, imam domen", "Ne, nemam domen", "Nisam siguran/sigurna", "Ne znam šta je domen"].map((label) => ({
          value: label,
          label,
        })),
      },
      {
        key: "domain_name",
        label: "Koji domen koristite?",
        type: "text",
        required: true,
        showWhen: (answers) => answers.domain_status === "Da, imam domen",
      },
      {
        key: "domain_help",
        label: "Da li želite pomoć oko izbora i registracije domena?",
        type: "single_choice",
        showWhen: (answers) => ["Ne, nemam domen", "Nisam siguran/sigurna"].includes(String(answers.domain_status || "")),
        options: ["Da", "Ne", "Možda kasnije"].map((label) => ({ value: label, label })),
      },
      {
        key: "hosting_status",
        label: "Da li imate hosting ili server?",
        type: "single_choice",
        required: true,
        options: [
          "Da, imam hosting/server",
          "Ne, nemam hosting/server",
          "Nisam siguran/sigurna",
          "Ne znam šta je hosting",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "hosting_type",
        label: "Koji hosting/server koristite?",
        type: "single_choice",
        showWhen: (answers) => answers.hosting_status === "Da, imam hosting/server",
        options: ["Shared hosting", "VPS server", "Dedicated server", "Cloud hosting", "Plesk/cPanel hosting", "Ne znam", "Drugo"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "hosting_other",
        label: "Unesite naziv hostinga/servera",
        type: "text",
        showWhen: (answers) => answers.hosting_type === "Drugo",
      },
      {
        key: "maintenance",
        label: "Da li želite da mi preuzmemo tehničko održavanje nakon izrade?",
        type: "single_choice",
        options: ["Da", "Ne", "Možda kasnije", "Želim prvo više informacija"].map((label) => ({ value: label, label })),
      },
    ],
  },
  {
    key: "presentation_module",
    eyebrow: "Modul",
    title: "Prezentacioni web sajt",
    description: "Struktura, sadržaj, funkcionalnosti i jezici za web prezentaciju.",
    projectTypes: ["presentation_website"],
    fields: [
      {
        key: "website_pages",
        label: "Koje stranice želite na sajtu?",
        type: "multiple_choice",
        required: true,
        options: [
          "Početna",
          "O nama",
          "Usluge",
          "Pojedinačne stranice usluga",
          "Portfolio / reference",
          "Tim",
          "Galerija",
          "Blog / novosti",
          "Cjenovnik",
          "Česta pitanja",
          "Kontakt",
          "Karijere",
          "Lokacije / poslovnice",
          "Pravne stranice",
          "Drugo",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "website_pages_other",
        label: "Navedite dodatne stranice",
        type: "textarea",
        showWhen: (answers) => Array.isArray(answers.website_pages) && answers.website_pages.includes("Drugo"),
      },
      {
        key: "website_content_status",
        label: "Da li imate pripremljen sadržaj za sajt?",
        type: "single_choice",
        required: true,
        options: [
          "Da, imamo tekstove i slike",
          "Imamo tekstove, ali ne i slike",
          "Imamo slike, ali ne i tekstove",
          "Imamo djelimičan sadržaj",
          "Nemamo sadržaj",
          "Treba nam kompletna pomoć oko sadržaja",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "website_features",
        label: "Koje funkcionalnosti želite?",
        type: "multiple_choice",
        options: [
          "Kontakt forma",
          "Forma za upit/ponudu",
          "Google mapa",
          "Blog sistem",
          "Galerija",
          "Prikaz referenci",
          "Newsletter prijava",
          "WhatsApp/Viber kontakt dugme",
          "Višejezičnost",
          "Admin panel za uređivanje sadržaja",
          "Osnovna SEO optimizacija",
          "Napredna SEO struktura",
          "Drugo",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "website_languages",
        label: "Da li sajt treba biti višejezičan?",
        type: "multiple_choice",
        required: true,
        options: ["Ne, samo jedan jezik", "B/H/S", "Engleski", "Njemački", "Italijanski", "Drugo", "Nisam siguran/sigurna"].map(
          (label) => ({ value: label, label }),
        ),
      },
    ],
  },
  {
    key: "ecommerce_module",
    eyebrow: "Modul",
    title: "Web shop / online prodavnica",
    description: "Proizvodi, plaćanje, dostava i administracija web shopa.",
    projectTypes: ["ecommerce"],
    fields: [
      {
        key: "product_count",
        label: "Koliko proizvoda planirate imati na početku?",
        type: "single_choice",
        required: true,
        options: ["1-20", "20-100", "100-500", "500-2000", "2000+", "Ne znam još"].map((label) => ({ value: label, label })),
      },
      {
        key: "product_variations",
        label: "Da li proizvodi imaju varijacije?",
        type: "single_choice",
        required: true,
        description: "Varijacije su npr. veličina, boja, model, kapacitet, težina ili pakovanje.",
        options: yesNoUnsure,
      },
      {
        key: "payment_methods",
        label: "Koje metode plaćanja želite?",
        type: "multiple_choice",
        required: true,
        options: [
          "Plaćanje pouzećem",
          "Bankovna uplata",
          "Kartično plaćanje",
          "Stripe",
          "PayPal",
          "Monri",
          "CorvusPay",
          "WSPay",
          "Kripto plaćanje",
          "Ne znam",
          "Drugo",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "delivery_methods",
        label: "Kako planirate organizovati dostavu?",
        type: "multiple_choice",
        required: true,
        options: ["Kurirska služba", "Vlastita dostava", "Lično preuzimanje", "Digitalni proizvodi", "Dostava nije potrebna", "Ne znam još"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "product_admin",
        label: "Kako želite unositi proizvode?",
        type: "single_choice",
        required: true,
        options: [
          "Ručno kroz admin panel",
          "Import iz Excel/CSV fajla",
          "API integracija sa drugim sistemom",
          "Automatska sinhronizacija sa dobavljačem",
          "Nisam siguran/sigurna",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "inventory_tracking",
        label: "Da li vam treba praćenje stanja zaliha?",
        type: "single_choice",
        required: true,
        options: ["Da", "Ne", "Možda kasnije", "Nisam siguran/sigurna"].map((label) => ({ value: label, label })),
      },
    ],
  },
  {
    key: "app_module",
    eyebrow: "Modul",
    title: "Web aplikacija / platforma",
    description: "Korisnici, uloge, funkcionalnosti, podaci i integracije.",
    projectTypes: ["web_application"],
    fields: [
      {
        key: "app_users",
        label: "Ko će koristiti aplikaciju?",
        type: "multiple_choice",
        required: true,
        options: ["Admin", "Registrovani korisnici", "Kupci", "Zaposleni", "Partneri", "Edukatori / mentori", "Moderatori", "Menadžeri", "Klijenti", "Drugo"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "user_accounts",
        label: "Da li korisnici trebaju imati svoje naloge?",
        type: "single_choice",
        required: true,
        options: yesNoUnsure,
      },
      {
        key: "account_features",
        label: "Koje funkcije korisnički nalog treba imati?",
        type: "multiple_choice",
        showWhen: (answers) => answers.user_accounts === "yes",
        options: [
          "Registracija",
          "Login",
          "Zaboravljena lozinka",
          "Profil korisnika",
          "Dashboard",
          "Notifikacije",
          "Historija aktivnosti",
          "Plaćanja",
          "Dokumenti/fajlovi",
          "Poruke",
          "Postavke naloga",
          "Drugo",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "app_features",
        label: "Koje funkcionalnosti očekujete u aplikaciji?",
        type: "multiple_choice",
        required: true,
        options: [
          "Admin panel",
          "Korisnički dashboard",
          "Uloge i permisije",
          "Upload fajlova",
          "Komentari",
          "Chat / messaging",
          "Email notifikacije",
          "Push notifikacije",
          "Kalendar",
          "Rezervacije",
          "Online plaćanje",
          "Pretplate / subscription",
          "Fakture",
          "Izvještaji",
          "Statistika",
          "API",
          "Integracije sa drugim sistemima",
          "Mobilna aplikacija kasnije",
          "Drugo",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "app_flow",
        label: "Opišite glavni tok korištenja aplikacije",
        type: "textarea",
        required: true,
        placeholder:
          "Primjer: Korisnik se registruje, kupuje paket, dobija pristup dashboardu, koristi funkcije i prima notifikacije.",
      },
      {
        key: "stored_data",
        label: "Koje podatke sistem treba čuvati?",
        type: "textarea",
      },
    ],
  },
  {
    key: "booking_module",
    eyebrow: "Modul",
    title: "Booking / rezervacijski sistem",
    description: "Tip rezervacija, dostupnost, plaćanje i podsjetnici.",
    projectTypes: ["booking_system"],
    fields: [
      {
        key: "booking_resource",
        label: "Šta korisnici rezervišu?",
        type: "single_choice",
        required: true,
        options: ["Termine", "Usluge", "Konsultacije", "Vozila", "Smještaj", "Stolove", "Prostorije", "Oprema/resurse", "Drugo"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "booking_availability",
        label: "Da li rezervacije zavise od dostupnosti?",
        type: "single_choice",
        required: true,
        options: yesNoUnsure,
      },
      {
        key: "booking_payment",
        label: "Da li korisnici trebaju online plaćati rezervaciju?",
        type: "single_choice",
        required: true,
        options: ["Da", "Ne", "Opcionalno", "Možda kasnije"].map((label) => ({ value: label, label })),
      },
      {
        key: "booking_reminders",
        label: "Da li želite automatske podsjetnike?",
        type: "multiple_choice",
        options: ["Email podsjetnik", "SMS podsjetnik", "WhatsApp/Viber podsjetnik", "Podsjetnik u aplikaciji", "Ne", "Možda kasnije"].map(
          (label) => ({ value: label, label }),
        ),
      },
    ],
  },
  {
    key: "landing_module",
    eyebrow: "Modul",
    title: "Landing page",
    description: "Cilj kampanje, glavna akcija i povezivanje sa oglasima.",
    projectTypes: ["landing_page"],
    fields: [
      {
        key: "landing_promotion",
        label: "Šta landing page treba promovisati?",
        type: "single_choice",
        required: true,
        options: ["Uslugu", "Proizvod", "Edukaciju", "Event", "Akciju/popust", "Prijavu na listu čekanja", "Preuzimanje dokumenta", "Konsultacije", "Drugo"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "landing_action",
        label: "Koja je glavna akcija koju posjetilac treba uraditi?",
        type: "single_choice",
        required: true,
        options: ["Poslati upit", "Kupiti proizvod", "Zakazati termin", "Prijaviti se", "Nazvati", "Poslati poruku", "Preuzeti dokument", "Ostaviti email", "Drugo"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "landing_campaigns",
        label: "Da li landing page treba biti povezan sa reklamnim kampanjama?",
        type: "multiple_choice",
        options: ["Google Ads", "Meta Ads", "TikTok Ads", "LinkedIn Ads", "Email kampanja", "Ne", "Nisam siguran/sigurna"].map(
          (label) => ({ value: label, label }),
        ),
      },
    ],
  },
  {
    key: "redesign_module",
    eyebrow: "Modul",
    title: "Redizajn",
    description: "Šta mijenjamo, šta zadržavamo i da li treba migracija podataka.",
    projectTypes: ["redesign"],
    fields: [
      {
        key: "redesign_changes",
        label: "Šta želite promijeniti na postojećem sajtu/aplikaciji?",
        type: "multiple_choice",
        required: true,
        options: ["Dizajn", "Brzinu", "Mobilnu verziju", "SEO", "Strukturu sadržaja", "Admin panel", "Funkcionalnosti", "Sigurnost", "Tehničku platformu", "Konverzije", "Drugo"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "keep_content",
        label: "Da li želite zadržati postojeći sadržaj?",
        type: "single_choice",
        required: true,
        options: ["Da, sav sadržaj", "Da, djelimično", "Ne, želimo novi sadržaj", "Nisam siguran/sigurna"].map((label) => ({
          value: label,
          label,
        })),
      },
      {
        key: "data_migration",
        label: "Da li želite migraciju postojećih podataka?",
        type: "single_choice",
        options: ["Da", "Ne", "Možda", "Nisam siguran/sigurna"].map((label) => ({ value: label, label })),
      },
      {
        key: "migration_data",
        label: "Koje podatke treba migrirati?",
        type: "multiple_choice",
        showWhen: (answers) => ["Da", "Možda"].includes(String(answers.data_migration || "")),
        options: ["Stranice", "Blog objave", "Proizvodi", "Korisnici", "Narudžbe", "Slike", "Dokumenti", "SEO meta podaci", "Drugo"].map(
          (label) => ({ value: label, label }),
        ),
      },
    ],
  },
  {
    key: "design_marketing",
    eyebrow: "Dizajn i marketing",
    title: "Vizuelni identitet, SEO i analitika",
    description: "Ovaj dio pomaže da procijenimo dizajn, sadržaj i marketinšku infrastrukturu.",
    fields: [
      {
        key: "brand_assets",
        label: "Da li imate postojeći vizuelni identitet?",
        type: "multiple_choice",
        options: ["Logo", "Boje", "Fontove", "Brand guide", "Fotografije", "Video materijale", "Nemamo vizuelni identitet", "Treba nam pomoć oko brendinga"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "visual_style",
        label: "Kakav vizuelni stil želite?",
        type: "multiple_choice",
        required: true,
        options: [
          "Moderan i minimalistički",
          "Premium/luksuzan",
          "Korporativan",
          "Kreativan i dinamičan",
          "Tech/startup",
          "Medicinski/profesionalan",
          "Topao i prijateljski",
          "Elegantno i jednostavno",
          "Ne znam, želim prijedlog",
          "Drugo",
        ].map((label) => ({ value: label, label })),
      },
      {
        key: "reference_sites",
        label: "Imate li primjere sajtova koji vam se sviđaju?",
        type: "textarea",
        placeholder: "Unesite linkove i napišite šta vam se sviđa kod njih.",
      },
      {
        key: "seo_importance",
        label: "Koliko vam je važna Google optimizacija / SEO?",
        type: "single_choice",
        required: true,
        description: "SEO je proces optimizacije sajta kako bi se bolje prikazivao na Google pretrazi.",
        options: ["Veoma važno", "Važno, ali osnovno", "Nije trenutno prioritet", "Ne znam šta je SEO", "Želim preporuku"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "analytics_tools",
        label: "Da li želite praćenje posjeta i ponašanja korisnika?",
        type: "multiple_choice",
        options: ["Google Analytics", "Google Search Console", "Google Tag Manager", "Meta Pixel", "TikTok Pixel", "Hotjar / Microsoft Clarity", "Nisam siguran/sigurna", "Ne"].map(
          (label) => ({ value: label, label }),
        ),
      },
    ],
  },
  {
    key: "content_legal",
    eyebrow: "Sadržaj i usklađenost",
    title: "Administracija, pravne stranice i cookie banner",
    description: "Planiramo ko priprema sadržaj, ko ga kasnije uređuje i koje pravne elemente treba uključiti.",
    fields: [
      {
        key: "content_owner",
        label: "Ko će pripremiti sadržaj?",
        type: "single_choice",
        required: true,
        options: ["Mi pripremamo sav sadržaj", "Vi pripremate sadržaj", "Zajedno pripremamo sadržaj", "Nemamo još definisano", "Treba nam kompletna pomoć"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "self_admin",
        label: "Da li želite sami uređivati sadržaj nakon završetka projekta?",
        type: "single_choice",
        required: true,
        options: ["Da", "Ne", "Djelimično", "Nisam siguran/sigurna"].map((label) => ({ value: label, label })),
      },
      {
        key: "editable_content",
        label: "Šta želite uređivati sami?",
        type: "multiple_choice",
        showWhen: (answers) => ["Da", "Djelimično"].includes(String(answers.self_admin || "")),
        options: ["Tekstove", "Slike", "Blog objave", "Proizvode", "Cijene", "Kategorije", "Korisnike", "Narudžbe", "Termine", "Stranice", "Drugo"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "legal_pages",
        label: "Da li vam trebaju pravne stranice?",
        type: "multiple_choice",
        options: ["Uslovi korištenja", "Politika privatnosti", "Cookie politika", "GDPR saglasnosti", "Pravila povrata/reklamacije", "Uslovi kupovine", "Nisam siguran/sigurna", "Ne"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "cookie_banner",
        label: "Da li sajt treba imati cookie consent/banner?",
        type: "single_choice",
        options: yesNoUnsure,
      },
    ],
  },
  {
    key: "budget_timeline",
    eyebrow: "Budžet i rokovi",
    title: "Okvir, početak i prioriteti",
    description: "Ovi odgovori pomažu da predložimo realan obim, faze i tehnologiju.",
    fields: [
      {
        key: "budget_range",
        label: "Koji okvirni budžet imate za projekat?",
        type: "single_choice",
        required: true,
        options: ["Do 500 €", "500-1.500 €", "1.500-3.000 €", "3.000-7.000 €", "7.000-15.000 €", "15.000 €+", "Želim prvo okvirnu procjenu", "Ne želim navesti budžet"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "desired_start",
        label: "Kada želite da projekat počne?",
        type: "single_choice",
        required: true,
        options: ["Odmah", "U narednih 30 dana", "U naredna 2-3 mjeseca", "Kasnije", "Nisam siguran/sigurna"].map((label) => ({
          value: label,
          label,
        })),
      },
      {
        key: "fixed_deadline",
        label: "Da li imate fiksni rok za završetak?",
        type: "single_choice",
        required: true,
        options: ["Da", "Ne", "Poželjno, ali nije strogo"].map((label) => ({ value: label, label })),
      },
      {
        key: "desired_deadline",
        label: "Unesite željeni rok",
        type: "date",
        showWhen: (answers) => ["Da", "Poželjno, ali nije strogo"].includes(String(answers.fixed_deadline || "")),
      },
      {
        key: "priorities",
        label: "Šta vam je najvažnije?",
        type: "ranking",
        description: "Kliknite prioritete redom važnosti. Ponovni klik uklanja prioritet.",
        options: ["Cijena", "Brzina izrade", "Kvalitet dizajna", "SEO", "Performanse", "Sigurnost", "Fleksibilnost sistema", "Dugoročna skalabilnost", "Jednostavno održavanje"].map(
          (label) => ({ value: label, label }),
        ),
      },
    ],
  },
  {
    key: "final",
    eyebrow: "Završni korak",
    title: "Još par detalja prije slanja",
    description: "Dodajte kontekst koji nije stao u prethodna pitanja i odaberite željeni sljedeći korak.",
    fields: [
      {
        key: "additional_notes",
        label: "Dodajte sve što mislite da je važno",
        type: "textarea",
      },
      {
        key: "next_step",
        label: "Šta želite kao sljedeći korak?",
        type: "single_choice",
        required: true,
        options: ["Želim okvirnu ponudu", "Želim konsultacije", "Želim tehnički prijedlog", "Želim prvo da analizirate moje odgovore", "Nisam siguran/sigurna"].map(
          (label) => ({ value: label, label }),
        ),
      },
      {
        key: "privacy_consent",
        label: "Saglasan/saglasna sam da Wizionar koristi dostavljene podatke za analizu upita i kontakt u vezi projekta.",
        type: "consent",
        required: true,
      },
    ],
  },
];

type StepText = Pick<InquiryStep, "eyebrow" | "title" | "description">;
type FieldText = Pick<InquiryField, "label" | "description" | "placeholder">;

const stepText: Record<Exclude<Language, "sr">, Record<string, StepText>> = {
  en: {
    contact: {
      eyebrow: "Basic information",
      title: "Who is contacting us?",
      description: "Details we need to contact you and understand the business context.",
    },
    classification: {
      eyebrow: "Classification",
      title: "What kind of project do you want to build?",
      description: "This answer decides which additional questions appear later.",
    },
    goals: {
      eyebrow: "Goals",
      title: "What should the project achieve?",
      description: "Select multiple answers if the project has several business goals.",
    },
    current_state: {
      eyebrow: "Current state",
      title: "Do you already have a digital solution?",
      description: "If you already have a website, shop or app, it helps to know what works and what needs improvement.",
    },
    technical_base: {
      eyebrow: "Domain and hosting",
      title: "Technical foundation",
      description: "A domain is your web address, while hosting is the server space where the site or app lives.",
    },
    presentation_module: {
      eyebrow: "Module",
      title: "Presentation website",
      description: "Structure, content, features and languages for a business website.",
    },
    ecommerce_module: {
      eyebrow: "Module",
      title: "Online shop",
      description: "Products, payments, delivery and shop administration.",
    },
    app_module: {
      eyebrow: "Module",
      title: "Web application / platform",
      description: "Users, roles, features, data and integrations.",
    },
    booking_module: {
      eyebrow: "Module",
      title: "Booking / reservation system",
      description: "Reservation type, availability, payments and reminders.",
    },
    landing_module: {
      eyebrow: "Module",
      title: "Landing page",
      description: "Campaign goal, main action and ad campaign connection.",
    },
    redesign_module: {
      eyebrow: "Module",
      title: "Redesign",
      description: "What we change, what we keep and whether data migration is needed.",
    },
    design_marketing: {
      eyebrow: "Design and marketing",
      title: "Visual identity, SEO and analytics",
      description: "This part helps us assess design, content and marketing infrastructure.",
    },
    content_legal: {
      eyebrow: "Content and compliance",
      title: "Administration, legal pages and cookie banner",
      description: "We plan who prepares content, who edits it later and which legal elements are needed.",
    },
    budget_timeline: {
      eyebrow: "Budget and timeline",
      title: "Budget, start date and priorities",
      description: "These answers help us suggest a realistic scope, phases and technology.",
    },
    final: {
      eyebrow: "Final step",
      title: "A few more details before sending",
      description: "Add context that did not fit previous questions and choose the desired next step.",
    },
  },
  de: {
    contact: {
      eyebrow: "Grunddaten",
      title: "Wer kontaktiert uns?",
      description: "Daten, die wir benötigen, um Sie zu kontaktieren und den Geschäftskontext zu verstehen.",
    },
    classification: {
      eyebrow: "Klassifizierung",
      title: "Welche Art von Projekt möchten Sie umsetzen?",
      description: "Diese Antwort bestimmt, welche zusätzlichen Fragen später angezeigt werden.",
    },
    goals: {
      eyebrow: "Ziele",
      title: "Was soll das Projekt erreichen?",
      description: "Wählen Sie mehrere Antworten, wenn das Projekt mehrere Geschäftsziele hat.",
    },
    current_state: {
      eyebrow: "Aktueller Stand",
      title: "Haben Sie bereits eine digitale Lösung?",
      description: "Wenn Sie bereits Website, Shop oder App haben, hilft uns zu wissen, was funktioniert und was verbessert werden soll.",
    },
    technical_base: {
      eyebrow: "Domain und Hosting",
      title: "Technische Grundlage",
      description: "Eine Domain ist Ihre Webadresse, Hosting ist der Serverplatz für Website oder App.",
    },
    presentation_module: {
      eyebrow: "Modul",
      title: "Präsentationswebsite",
      description: "Struktur, Inhalte, Funktionen und Sprachen für eine Unternehmenswebsite.",
    },
    ecommerce_module: {
      eyebrow: "Modul",
      title: "Online-Shop",
      description: "Produkte, Zahlungen, Lieferung und Shop-Administration.",
    },
    app_module: {
      eyebrow: "Modul",
      title: "Webanwendung / Plattform",
      description: "Benutzer, Rollen, Funktionen, Daten und Integrationen.",
    },
    booking_module: {
      eyebrow: "Modul",
      title: "Buchungs- / Reservierungssystem",
      description: "Reservierungstyp, Verfügbarkeit, Zahlungen und Erinnerungen.",
    },
    landing_module: {
      eyebrow: "Modul",
      title: "Landingpage",
      description: "Kampagnenziel, Hauptaktion und Verbindung zu Werbekampagnen.",
    },
    redesign_module: {
      eyebrow: "Modul",
      title: "Redesign",
      description: "Was geändert wird, was erhalten bleibt und ob Datenmigration nötig ist.",
    },
    design_marketing: {
      eyebrow: "Design und Marketing",
      title: "Visuelle Identität, SEO und Analytics",
      description: "Dieser Teil hilft uns, Design, Inhalte und Marketing-Infrastruktur einzuschätzen.",
    },
    content_legal: {
      eyebrow: "Inhalte und Compliance",
      title: "Administration, rechtliche Seiten und Cookie-Banner",
      description: "Wir planen, wer Inhalte vorbereitet, wer sie später bearbeitet und welche rechtlichen Elemente nötig sind.",
    },
    budget_timeline: {
      eyebrow: "Budget und Zeitplan",
      title: "Budget, Start und Prioritäten",
      description: "Diese Antworten helfen uns, realistischen Umfang, Phasen und Technologie vorzuschlagen.",
    },
    final: {
      eyebrow: "Letzter Schritt",
      title: "Ein paar Details vor dem Absenden",
      description: "Fügen Sie Kontext hinzu, der in den vorherigen Fragen keinen Platz hatte, und wählen Sie den nächsten Schritt.",
    },
  },
  it: {
    contact: {
      eyebrow: "Dati di base",
      title: "Chi ci sta contattando?",
      description: "Informazioni necessarie per contattarti e capire il contesto aziendale.",
    },
    classification: {
      eyebrow: "Classificazione",
      title: "Che tipo di progetto vuoi realizzare?",
      description: "Questa risposta determina quali domande aggiuntive verranno mostrate in seguito.",
    },
    goals: {
      eyebrow: "Obiettivi",
      title: "Cosa deve ottenere il progetto?",
      description: "Seleziona più risposte se il progetto ha più obiettivi di business.",
    },
    current_state: {
      eyebrow: "Stato attuale",
      title: "Hai già una soluzione digitale?",
      description: "Se hai già un sito, shop o app, è utile sapere cosa funziona e cosa va migliorato.",
    },
    technical_base: {
      eyebrow: "Dominio e hosting",
      title: "Base tecnica",
      description: "Il dominio è l'indirizzo web, mentre l'hosting è lo spazio/server dove vive il sito o l'app.",
    },
    presentation_module: {
      eyebrow: "Modulo",
      title: "Sito web di presentazione",
      description: "Struttura, contenuti, funzionalità e lingue per un sito aziendale.",
    },
    ecommerce_module: {
      eyebrow: "Modulo",
      title: "Shop online",
      description: "Prodotti, pagamenti, consegna e amministrazione dello shop.",
    },
    app_module: {
      eyebrow: "Modulo",
      title: "Applicazione web / piattaforma",
      description: "Utenti, ruoli, funzionalità, dati e integrazioni.",
    },
    booking_module: {
      eyebrow: "Modulo",
      title: "Sistema booking / prenotazioni",
      description: "Tipo di prenotazione, disponibilità, pagamenti e promemoria.",
    },
    landing_module: {
      eyebrow: "Modulo",
      title: "Landing page",
      description: "Obiettivo della campagna, azione principale e collegamento con gli annunci.",
    },
    redesign_module: {
      eyebrow: "Modulo",
      title: "Redesign",
      description: "Cosa cambiare, cosa mantenere e se serve migrare dati.",
    },
    design_marketing: {
      eyebrow: "Design e marketing",
      title: "Identità visiva, SEO e analytics",
      description: "Questa parte ci aiuta a valutare design, contenuti e infrastruttura marketing.",
    },
    content_legal: {
      eyebrow: "Contenuti e conformità",
      title: "Amministrazione, pagine legali e cookie banner",
      description: "Pianifichiamo chi prepara i contenuti, chi li gestirà dopo e quali elementi legali servono.",
    },
    budget_timeline: {
      eyebrow: "Budget e tempi",
      title: "Budget, inizio e priorità",
      description: "Queste risposte aiutano a proporre ambito, fasi e tecnologia realistici.",
    },
    final: {
      eyebrow: "Ultimo passo",
      title: "Ancora pochi dettagli prima dell'invio",
      description: "Aggiungi contesto non coperto dalle domande precedenti e scegli il prossimo passo desiderato.",
    },
  },
};

const fieldText: Record<Exclude<Language, "sr">, Record<string, FieldText>> = {
  en: {
    full_name: { label: "Full name" },
    company_name: { label: "Company / project name" },
    email: { label: "Email address" },
    phone: { label: "Phone" },
    location: { label: "Country / city" },
    business_description: {
      label: "What do you do?",
      placeholder: "Briefly describe your company, services, products or idea.",
    },
    project_type: { label: "Project type" },
    idea_if_unsure: { label: "If you are not sure, describe the idea in your own words" },
    main_goals: { label: "Main project goal" },
    other_goal: { label: "Describe the other goal" },
    project_description: {
      label: "What should users be able to do on your site or app?",
      placeholder: "Example: browse services, send an inquiry, buy a product, book an appointment, log in or use a dashboard.",
    },
    existing_solution_status: { label: "Do you currently have a website, online shop or application?" },
    existing_solution_url: { label: "Existing website / application link" },
    existing_solution_pain_points: { label: "What bothers you most about the current solution?" },
    existing_solution_other_problem: { label: "Describe the problem" },
    domain_status: { label: "Do you have a domain?" },
    domain_name: { label: "Which domain do you use?" },
    domain_help: { label: "Would you like help choosing and registering a domain?" },
    hosting_status: { label: "Do you have hosting or a server?" },
    hosting_type: { label: "Which hosting/server do you use?" },
    hosting_other: { label: "Enter the hosting/server name" },
    maintenance: { label: "Would you like us to take over technical maintenance after launch?" },
    website_pages: { label: "Which pages do you want on the website?" },
    website_pages_other: { label: "List additional pages" },
    website_content_status: { label: "Do you have content prepared for the website?" },
    website_features: { label: "Which features do you want?" },
    website_languages: { label: "Should the website be multilingual?" },
    product_count: { label: "How many products do you plan to have at the start?" },
    product_variations: {
      label: "Do products have variations?",
      description: "Variations include size, color, model, capacity, weight or packaging.",
    },
    payment_methods: { label: "Which payment methods do you want?" },
    delivery_methods: { label: "How do you plan to organize delivery?" },
    product_admin: { label: "How do you want to enter products?" },
    inventory_tracking: { label: "Do you need inventory tracking?" },
    app_users: { label: "Who will use the application?" },
    user_accounts: { label: "Do users need their own accounts?" },
    account_features: { label: "Which features should a user account have?" },
    app_features: { label: "Which features do you expect in the application?" },
    app_flow: {
      label: "Describe the main application flow",
      placeholder: "Example: The user registers, buys a package, gets dashboard access, uses features and receives notifications.",
    },
    stored_data: { label: "Which data should the system store?" },
    booking_resource: { label: "What do users reserve?" },
    booking_availability: { label: "Do reservations depend on availability?" },
    booking_payment: { label: "Should users pay for reservations online?" },
    booking_reminders: { label: "Do you want automatic reminders?" },
    landing_promotion: { label: "What should the landing page promote?" },
    landing_action: { label: "What is the main action visitors should take?" },
    landing_campaigns: { label: "Should the landing page be connected to ad campaigns?" },
    redesign_changes: { label: "What do you want to change on the existing site/app?" },
    keep_content: { label: "Do you want to keep existing content?" },
    data_migration: { label: "Do you want existing data migrated?" },
    migration_data: { label: "Which data should be migrated?" },
    brand_assets: { label: "Do you have an existing visual identity?" },
    visual_style: { label: "What visual style do you want?" },
    reference_sites: {
      label: "Do you have examples of websites you like?",
      placeholder: "Enter links and describe what you like about them.",
    },
    seo_importance: {
      label: "How important is Google optimization / SEO?",
      description: "SEO is the process of optimizing a site so it appears better in Google search.",
    },
    analytics_tools: { label: "Do you want visitor and behavior tracking?" },
    content_owner: { label: "Who will prepare the content?" },
    self_admin: { label: "Do you want to edit content yourself after project completion?" },
    editable_content: { label: "What do you want to edit yourself?" },
    legal_pages: { label: "Do you need legal pages?" },
    cookie_banner: { label: "Should the site have a cookie consent/banner?" },
    budget_range: { label: "What approximate budget do you have for the project?" },
    desired_start: { label: "When do you want the project to start?" },
    fixed_deadline: { label: "Do you have a fixed completion deadline?" },
    desired_deadline: { label: "Enter the desired deadline", placeholder: "dd.mm.yyyy" },
    priorities: {
      label: "What is most important to you?",
      description: "Click priorities in order of importance. Click again to remove a priority.",
    },
    additional_notes: { label: "Add anything you think is important" },
    next_step: { label: "What would you like as the next step?" },
    privacy_consent: {
      label: "I agree that Wizionar may use the submitted data to analyze the inquiry and contact me about the project.",
    },
  },
  de: {
    full_name: { label: "Vor- und Nachname" },
    company_name: { label: "Firma / Projektname" },
    email: { label: "Email-Adresse" },
    phone: { label: "Telefon" },
    location: { label: "Land / Stadt" },
    business_description: {
      label: "Was machen Sie?",
      placeholder: "Beschreiben Sie kurz Ihr Unternehmen, Ihre Leistungen, Produkte oder Idee.",
    },
    project_type: { label: "Projekttyp" },
    idea_if_unsure: { label: "Wenn Sie nicht sicher sind, beschreiben Sie die Idee in Ihren eigenen Worten" },
    main_goals: { label: "Hauptziel des Projekts" },
    other_goal: { label: "Beschreiben Sie das andere Ziel" },
    project_description: {
      label: "Was sollen Benutzer auf Ihrer Website oder App tun können?",
      placeholder: "Beispiel: Leistungen ansehen, Anfrage senden, Produkt kaufen, Termin buchen, einloggen oder Dashboard nutzen.",
    },
    existing_solution_status: { label: "Haben Sie aktuell eine Website, einen Online-Shop oder eine Anwendung?" },
    existing_solution_url: { label: "Link zur bestehenden Website / Anwendung" },
    existing_solution_pain_points: { label: "Was stört Sie am meisten an der aktuellen Lösung?" },
    existing_solution_other_problem: { label: "Beschreiben Sie das Problem" },
    domain_status: { label: "Haben Sie eine Domain?" },
    domain_name: { label: "Welche Domain nutzen Sie?" },
    domain_help: { label: "Möchten Sie Hilfe bei Auswahl und Registrierung der Domain?" },
    hosting_status: { label: "Haben Sie Hosting oder einen Server?" },
    hosting_type: { label: "Welches Hosting / welchen Server nutzen Sie?" },
    hosting_other: { label: "Hosting-/Servernamen eingeben" },
    maintenance: { label: "Möchten Sie, dass wir nach Fertigstellung die technische Wartung übernehmen?" },
    website_pages: { label: "Welche Seiten wünschen Sie auf der Website?" },
    website_pages_other: { label: "Weitere Seiten angeben" },
    website_content_status: { label: "Haben Sie Inhalte für die Website vorbereitet?" },
    website_features: { label: "Welche Funktionen wünschen Sie?" },
    website_languages: { label: "Soll die Website mehrsprachig sein?" },
    product_count: { label: "Wie viele Produkte planen Sie zu Beginn?" },
    product_variations: {
      label: "Haben Produkte Varianten?",
      description: "Varianten sind z. B. Größe, Farbe, Modell, Kapazität, Gewicht oder Verpackung.",
    },
    payment_methods: { label: "Welche Zahlungsmethoden wünschen Sie?" },
    delivery_methods: { label: "Wie planen Sie die Lieferung zu organisieren?" },
    product_admin: { label: "Wie möchten Sie Produkte einpflegen?" },
    inventory_tracking: { label: "Benötigen Sie Lagerbestandsverfolgung?" },
    app_users: { label: "Wer wird die Anwendung nutzen?" },
    user_accounts: { label: "Benötigen Benutzer eigene Konten?" },
    account_features: { label: "Welche Funktionen soll ein Benutzerkonto haben?" },
    app_features: { label: "Welche Funktionen erwarten Sie in der Anwendung?" },
    app_flow: {
      label: "Beschreiben Sie den Hauptablauf der Anwendung",
      placeholder: "Beispiel: Der Benutzer registriert sich, kauft ein Paket, erhält Dashboard-Zugang, nutzt Funktionen und bekommt Benachrichtigungen.",
    },
    stored_data: { label: "Welche Daten soll das System speichern?" },
    booking_resource: { label: "Was reservieren die Benutzer?" },
    booking_availability: { label: "Hängen Reservierungen von Verfügbarkeit ab?" },
    booking_payment: { label: "Sollen Benutzer Reservierungen online bezahlen?" },
    booking_reminders: { label: "Möchten Sie automatische Erinnerungen?" },
    landing_promotion: { label: "Was soll die Landingpage bewerben?" },
    landing_action: { label: "Welche Hauptaktion sollen Besucher ausführen?" },
    landing_campaigns: { label: "Soll die Landingpage mit Werbekampagnen verbunden sein?" },
    redesign_changes: { label: "Was möchten Sie an der bestehenden Website/App ändern?" },
    keep_content: { label: "Möchten Sie bestehende Inhalte behalten?" },
    data_migration: { label: "Möchten Sie bestehende Daten migrieren?" },
    migration_data: { label: "Welche Daten sollen migriert werden?" },
    brand_assets: { label: "Haben Sie eine bestehende visuelle Identität?" },
    visual_style: { label: "Welchen visuellen Stil wünschen Sie?" },
    reference_sites: {
      label: "Haben Sie Beispiele von Websites, die Ihnen gefallen?",
      placeholder: "Fügen Sie Links ein und beschreiben Sie, was Ihnen daran gefällt.",
    },
    seo_importance: {
      label: "Wie wichtig ist Google-Optimierung / SEO?",
      description: "SEO ist die Optimierung der Website, damit sie in der Google-Suche besser erscheint.",
    },
    analytics_tools: { label: "Möchten Sie Besuche und Nutzerverhalten messen?" },
    content_owner: { label: "Wer bereitet die Inhalte vor?" },
    self_admin: { label: "Möchten Sie Inhalte nach Projektabschluss selbst bearbeiten?" },
    editable_content: { label: "Was möchten Sie selbst bearbeiten?" },
    legal_pages: { label: "Benötigen Sie rechtliche Seiten?" },
    cookie_banner: { label: "Soll die Website einen Cookie-Consent/Banner haben?" },
    budget_range: { label: "Welches ungefähre Budget haben Sie für das Projekt?" },
    desired_start: { label: "Wann soll das Projekt starten?" },
    fixed_deadline: { label: "Haben Sie einen festen Fertigstellungstermin?" },
    desired_deadline: { label: "Gewünschten Termin eingeben", placeholder: "tt.mm.jjjj" },
    priorities: {
      label: "Was ist Ihnen am wichtigsten?",
      description: "Klicken Sie Prioritäten in Reihenfolge der Wichtigkeit. Ein weiterer Klick entfernt sie.",
    },
    additional_notes: { label: "Fügen Sie alles hinzu, was Sie wichtig finden" },
    next_step: { label: "Was wünschen Sie als nächsten Schritt?" },
    privacy_consent: {
      label: "Ich stimme zu, dass Wizionar die übermittelten Daten zur Analyse der Anfrage und zur Kontaktaufnahme zum Projekt verwendet.",
    },
  },
  it: {
    full_name: { label: "Nome e cognome" },
    company_name: { label: "Nome azienda / progetto" },
    email: { label: "Indirizzo email" },
    phone: { label: "Telefono" },
    location: { label: "Paese / città" },
    business_description: {
      label: "Di cosa ti occupi?",
      placeholder: "Descrivi brevemente azienda, servizi, prodotti o idea.",
    },
    project_type: { label: "Tipo di progetto" },
    idea_if_unsure: { label: "Se non sei sicuro, descrivi l'idea con parole tue" },
    main_goals: { label: "Obiettivo principale del progetto" },
    other_goal: { label: "Descrivi l'altro obiettivo" },
    project_description: {
      label: "Cosa deve poter fare l'utente sul sito o nell'app?",
      placeholder: "Esempio: vedere servizi, inviare richiesta, acquistare prodotto, prenotare appuntamento, accedere o usare dashboard.",
    },
    existing_solution_status: { label: "Hai attualmente un sito web, shop online o applicazione?" },
    existing_solution_url: { label: "Link al sito / applicazione esistente" },
    existing_solution_pain_points: { label: "Cosa ti dà più fastidio nella soluzione attuale?" },
    existing_solution_other_problem: { label: "Descrivi il problema" },
    domain_status: { label: "Hai un dominio?" },
    domain_name: { label: "Quale dominio usi?" },
    domain_help: { label: "Vuoi aiuto nella scelta e registrazione del dominio?" },
    hosting_status: { label: "Hai hosting o server?" },
    hosting_type: { label: "Quale hosting/server usi?" },
    hosting_other: { label: "Inserisci il nome dell'hosting/server" },
    maintenance: { label: "Vuoi che gestiamo noi la manutenzione tecnica dopo la realizzazione?" },
    website_pages: { label: "Quali pagine vuoi nel sito?" },
    website_pages_other: { label: "Indica pagine aggiuntive" },
    website_content_status: { label: "Hai contenuti pronti per il sito?" },
    website_features: { label: "Quali funzionalità vuoi?" },
    website_languages: { label: "Il sito deve essere multilingua?" },
    product_count: { label: "Quanti prodotti prevedi all'inizio?" },
    product_variations: {
      label: "I prodotti hanno varianti?",
      description: "Le varianti sono ad esempio taglia, colore, modello, capacità, peso o confezione.",
    },
    payment_methods: { label: "Quali metodi di pagamento vuoi?" },
    delivery_methods: { label: "Come pensi di organizzare la consegna?" },
    product_admin: { label: "Come vuoi inserire i prodotti?" },
    inventory_tracking: { label: "Ti serve il monitoraggio delle scorte?" },
    app_users: { label: "Chi userà l'applicazione?" },
    user_accounts: { label: "Gli utenti devono avere account propri?" },
    account_features: { label: "Quali funzioni deve avere l'account utente?" },
    app_features: { label: "Quali funzionalità ti aspetti nell'applicazione?" },
    app_flow: {
      label: "Descrivi il flusso principale dell'applicazione",
      placeholder: "Esempio: l'utente si registra, acquista un pacchetto, accede alla dashboard, usa funzioni e riceve notifiche.",
    },
    stored_data: { label: "Quali dati deve salvare il sistema?" },
    booking_resource: { label: "Cosa prenotano gli utenti?" },
    booking_availability: { label: "Le prenotazioni dipendono dalla disponibilità?" },
    booking_payment: { label: "Gli utenti devono pagare online la prenotazione?" },
    booking_reminders: { label: "Vuoi promemoria automatici?" },
    landing_promotion: { label: "Cosa deve promuovere la landing page?" },
    landing_action: { label: "Qual è l'azione principale che il visitatore deve compiere?" },
    landing_campaigns: { label: "La landing page deve essere collegata a campagne pubblicitarie?" },
    redesign_changes: { label: "Cosa vuoi cambiare nel sito/app esistente?" },
    keep_content: { label: "Vuoi mantenere i contenuti esistenti?" },
    data_migration: { label: "Vuoi migrare dati esistenti?" },
    migration_data: { label: "Quali dati devono essere migrati?" },
    brand_assets: { label: "Hai un'identità visiva esistente?" },
    visual_style: { label: "Che stile visivo desideri?" },
    reference_sites: {
      label: "Hai esempi di siti che ti piacciono?",
      placeholder: "Inserisci link e scrivi cosa ti piace.",
    },
    seo_importance: {
      label: "Quanto è importante l'ottimizzazione Google / SEO?",
      description: "La SEO è il processo di ottimizzazione del sito per apparire meglio nella ricerca Google.",
    },
    analytics_tools: { label: "Vuoi tracciare visite e comportamento utenti?" },
    content_owner: { label: "Chi preparerà i contenuti?" },
    self_admin: { label: "Vuoi modificare i contenuti autonomamente dopo il completamento?" },
    editable_content: { label: "Cosa vuoi modificare da solo?" },
    legal_pages: { label: "Ti servono pagine legali?" },
    cookie_banner: { label: "Il sito deve avere cookie consent/banner?" },
    budget_range: { label: "Qual è il budget indicativo per il progetto?" },
    desired_start: { label: "Quando vuoi che inizi il progetto?" },
    fixed_deadline: { label: "Hai una scadenza fissa per il completamento?" },
    desired_deadline: { label: "Inserisci la scadenza desiderata", placeholder: "gg.mm.aaaa" },
    priorities: {
      label: "Cosa è più importante per te?",
      description: "Clicca le priorità in ordine di importanza. Un altro clic rimuove la priorità.",
    },
    additional_notes: { label: "Aggiungi tutto ciò che ritieni importante" },
    next_step: { label: "Cosa desideri come prossimo passo?" },
    privacy_consent: {
      label: "Accetto che Wizionar utilizzi i dati inviati per analizzare la richiesta e contattarmi sul progetto.",
    },
  },
};

const optionText: Record<Exclude<Language, "sr">, Record<string, string>> = {
  en: {
    Da: "Yes",
    Ne: "No",
    "Nisam siguran/sigurna": "Not sure",
    "Možda kasnije": "Maybe later",
    "Ne znam": "I don't know",
    Drugo: "Other",
    yes: "Yes",
    no: "No",
    not_sure: "Not sure",
    "Prezentacioni web sajt": "Presentation website",
    "Web shop / online prodavnica": "Online shop",
    "Web aplikacija / platforma": "Web application / platform",
    "Booking / rezervacijski sistem": "Booking / reservation system",
    "Landing page": "Landing page",
    "Redizajn postojećeg sajta ili aplikacije": "Redesign of an existing site or application",
    "Predstavljanje firme ili usluga": "Presenting a company or services",
    "Povećanje broja upita": "Increasing the number of inquiries",
    "Online prodaja proizvoda": "Online product sales",
    "Online prodaja usluga": "Online service sales",
    "Automatizacija poslovnog procesa": "Business process automation",
    "Rezervacija termina": "Appointment booking",
    "Upravljanje korisnicima": "User management",
    "Edukacija korisnika": "User education",
    "Kreiranje zajednice / community sistema": "Community system",
    "Interni poslovni sistem": "Internal business system",
    "SaaS aplikacija": "SaaS application",
    "Marketplace/platforma": "Marketplace/platform",
    "Bolji SEO i Google vidljivost": "Better SEO and Google visibility",
    "Bolji dizajn i korisničko iskustvo": "Better design and user experience",
    "U izradi je": "It is in progress",
    "Zastarjeli dizajn": "Outdated design",
    "Spor sajt": "Slow site",
    "Loša mobilna verzija": "Poor mobile version",
    "Loša Google vidljivost": "Poor Google visibility",
    "Teško uređivanje sadržaja": "Difficult content editing",
    "Nema admin panel": "No admin panel",
    "Nema online plaćanje": "No online payment",
    "Loše korisničko iskustvo": "Poor user experience",
    "Nedostaju funkcionalnosti": "Missing features",
    "Tehnički problemi": "Technical issues",
    "Sigurnosni problemi": "Security issues",
    "Da, imam domen": "Yes, I have a domain",
    "Ne, nemam domen": "No, I do not have a domain",
    "Ne znam šta je domen": "I do not know what a domain is",
    "Da, imam hosting/server": "Yes, I have hosting/server",
    "Ne, nemam hosting/server": "No, I do not have hosting/server",
    "Ne znam šta je hosting": "I do not know what hosting is",
    "Želim prvo više informacija": "I want more information first",
    Početna: "Home",
    "O nama": "About us",
    Usluge: "Services",
    "Pojedinačne stranice usluga": "Individual service pages",
    "Portfolio / reference": "Portfolio / references",
    Tim: "Team",
    Galerija: "Gallery",
    "Blog / novosti": "Blog / news",
    Cjenovnik: "Price list",
    "Česta pitanja": "FAQ",
    Kontakt: "Contact",
    Karijere: "Careers",
    "Lokacije / poslovnice": "Locations / branches",
    "Pravne stranice": "Legal pages",
    "Da, imamo tekstove i slike": "Yes, we have text and images",
    "Imamo tekstove, ali ne i slike": "We have text, but not images",
    "Imamo slike, ali ne i tekstove": "We have images, but not text",
    "Imamo djelimičan sadržaj": "We have partial content",
    "Nemamo sadržaj": "We do not have content",
    "Treba nam kompletna pomoć oko sadržaja": "We need full help with content",
    "Kontakt forma": "Contact form",
    "Forma za upit/ponudu": "Inquiry/quote form",
    "Google mapa": "Google map",
    "Blog sistem": "Blog system",
    "Prikaz referenci": "Reference display",
    "Newsletter prijava": "Newsletter signup",
    "WhatsApp/Viber kontakt dugme": "WhatsApp/Viber contact button",
    Višejezičnost: "Multilingual support",
    "Admin panel za uređivanje sadržaja": "Admin panel for content editing",
    "Osnovna SEO optimizacija": "Basic SEO optimization",
    "Napredna SEO struktura": "Advanced SEO structure",
    "Ne, samo jedan jezik": "No, one language only",
    "Engleski": "English",
    "Njemački": "German",
    "Italijanski": "Italian",
    "Ne znam još": "I do not know yet",
    "Plaćanje pouzećem": "Cash on delivery",
    "Bankovna uplata": "Bank transfer",
    "Kartično plaćanje": "Card payment",
    "Kripto plaćanje": "Crypto payment",
    "Kurirska služba": "Courier service",
    "Vlastita dostava": "Own delivery",
    "Lično preuzimanje": "Personal pickup",
    "Digitalni proizvodi": "Digital products",
    "Dostava nije potrebna": "Delivery is not needed",
    "Ručno kroz admin panel": "Manually through admin panel",
    "Import iz Excel/CSV fajla": "Import from Excel/CSV file",
    "API integracija sa drugim sistemom": "API integration with another system",
    "Automatska sinhronizacija sa dobavljačem": "Automatic supplier synchronization",
    "Registrovani korisnici": "Registered users",
    Kupci: "Customers",
    Zaposleni: "Employees",
    Partneri: "Partners",
    "Edukatori / mentori": "Educators / mentors",
    Moderatori: "Moderators",
    Menadžeri: "Managers",
    Klijenti: "Clients",
    Registracija: "Registration",
    "Zaboravljena lozinka": "Forgot password",
    "Profil korisnika": "User profile",
    Notifikacije: "Notifications",
    "Historija aktivnosti": "Activity history",
    Plaćanja: "Payments",
    "Dokumenti/fajlovi": "Documents/files",
    Poruke: "Messages",
    "Postavke naloga": "Account settings",
    "Korisnički dashboard": "User dashboard",
    "Uloge i permisije": "Roles and permissions",
    "Upload fajlova": "File upload",
    Komentari: "Comments",
    "Chat / messaging": "Chat / messaging",
    "Email notifikacije": "Email notifications",
    "Push notifikacije": "Push notifications",
    Kalendar: "Calendar",
    Rezervacije: "Bookings",
    "Online plaćanje": "Online payment",
    "Pretplate / subscription": "Subscriptions",
    Fakture: "Invoices",
    Izvještaji: "Reports",
    Statistika: "Statistics",
    "Integracije sa drugim sistemima": "Integrations with other systems",
    "Mobilna aplikacija kasnije": "Mobile app later",
    Konsultacije: "Consultations",
    Vozila: "Vehicles",
    Smještaj: "Accommodation",
    Stolove: "Tables",
    Prostorije: "Rooms",
    "Oprema/resurse": "Equipment/resources",
    Opcionalno: "Optional",
    "Email podsjetnik": "Email reminder",
    "SMS podsjetnik": "SMS reminder",
    "WhatsApp/Viber podsjetnik": "WhatsApp/Viber reminder",
    "Podsjetnik u aplikaciji": "In-app reminder",
    Uslugu: "Service",
    Proizvod: "Product",
    Edukaciju: "Education",
    Event: "Event",
    "Akciju/popust": "Promotion/discount",
    "Prijavu na listu čekanja": "Waitlist signup",
    "Preuzimanje dokumenta": "Document download",
    "Poslati upit": "Send inquiry",
    "Kupiti proizvod": "Buy product",
    "Zakazati termin": "Book appointment",
    "Prijaviti se": "Sign up",
    Nazvati: "Call",
    "Poslati poruku": "Send message",
    "Preuzeti dokument": "Download document",
    "Ostaviti email": "Leave email",
    "Email kampanja": "Email campaign",
    Dizajn: "Design",
    Brzinu: "Speed",
    "Mobilnu verziju": "Mobile version",
    "Strukturu sadržaja": "Content structure",
    Sigurnost: "Security",
    "Tehničku platformu": "Technical platform",
    Konverzije: "Conversions",
    "Da, sav sadržaj": "Yes, all content",
    "Da, djelimično": "Yes, partially",
    "Ne, želimo novi sadržaj": "No, we want new content",
    Možda: "Maybe",
    Stranice: "Pages",
    "Blog objave": "Blog posts",
    Proizvodi: "Products",
    Korisnici: "Users",
    Narudžbe: "Orders",
    Slike: "Images",
    Dokumenti: "Documents",
    "SEO meta podaci": "SEO metadata",
    Boje: "Colors",
    Fontove: "Fonts",
    Fotografije: "Photos",
    "Video materijale": "Video materials",
    "Nemamo vizuelni identitet": "We do not have a visual identity",
    "Treba nam pomoć oko brendinga": "We need branding help",
    "Moderan i minimalistički": "Modern and minimalist",
    "Premium/luksuzan": "Premium/luxury",
    Korporativan: "Corporate",
    "Kreativan i dinamičan": "Creative and dynamic",
    "Medicinski/profesionalan": "Medical/professional",
    "Topao i prijateljski": "Warm and friendly",
    "Elegantno i jednostavno": "Elegant and simple",
    "Ne znam, želim prijedlog": "I don't know, I want a suggestion",
    "Veoma važno": "Very important",
    "Važno, ali osnovno": "Important, but basic",
    "Nije trenutno prioritet": "Not a current priority",
    "Ne znam šta je SEO": "I do not know what SEO is",
    "Želim preporuku": "I want a recommendation",
    "Google Analytics": "Google Analytics",
    "Google Search Console": "Google Search Console",
    "Google Tag Manager": "Google Tag Manager",
    "Meta Pixel": "Meta Pixel",
    "TikTok Pixel": "TikTok Pixel",
    "Hotjar / Microsoft Clarity": "Hotjar / Microsoft Clarity",
    "Mi pripremamo sav sadržaj": "We prepare all content",
    "Vi pripremate sadržaj": "You prepare content",
    "Zajedno pripremamo sadržaj": "We prepare content together",
    "Nemamo još definisano": "We have not defined it yet",
    "Treba nam kompletna pomoć": "We need full help",
    Djelimično: "Partially",
    Tekstove: "Texts",
    Cijene: "Prices",
    Kategorije: "Categories",
    Termine: "Appointments",
    "Uslovi korištenja": "Terms of use",
    "Politika privatnosti": "Privacy policy",
    "Cookie politika": "Cookie policy",
    "GDPR saglasnosti": "GDPR consents",
    "Pravila povrata/reklamacije": "Return/complaint rules",
    "Uslovi kupovine": "Purchase terms",
    "Do 500 €": "Up to 500 €",
    "Želim prvo okvirnu procjenu": "I want an estimate first",
    "Ne želim navesti budžet": "I do not want to state a budget",
    Odmah: "Immediately",
    "U narednih 30 dana": "In the next 30 days",
    "U naredna 2-3 mjeseca": "In the next 2-3 months",
    Kasnije: "Later",
    "Poželjno, ali nije strogo": "Preferred, but not strict",
    Cijena: "Price",
    "Brzina izrade": "Development speed",
    "Kvalitet dizajna": "Design quality",
    Performanse: "Performance",
    "Fleksibilnost sistema": "System flexibility",
    "Dugoročna skalabilnost": "Long-term scalability",
    "Jednostavno održavanje": "Easy maintenance",
    "Želim okvirnu ponudu": "I want an estimate",
    "Želim konsultacije": "I want a consultation",
    "Želim tehnički prijedlog": "I want a technical proposal",
    "Želim prvo da analizirate moje odgovore": "I want you to analyze my answers first",
  },
  de: {},
  it: {},
};

optionText.de = {
  ...optionText.en,
  Da: "Ja",
  Ne: "Nein",
  "Nisam siguran/sigurna": "Nicht sicher",
  "Možda kasnije": "Vielleicht später",
  "Ne znam": "Ich weiß nicht",
  Drugo: "Andere",
  yes: "Ja",
  no: "Nein",
  not_sure: "Nicht sicher",
  "Prezentacioni web sajt": "Präsentationswebsite",
  "Web shop / online prodavnica": "Online-Shop",
  "Web aplikacija / platforma": "Webanwendung / Plattform",
  "Booking / rezervacijski sistem": "Buchungs- / Reservierungssystem",
  "Redizajn postojećeg sajta ili aplikacije": "Redesign einer bestehenden Website oder Anwendung",
  "Predstavljanje firme ili usluga": "Unternehmen oder Leistungen präsentieren",
  "Povećanje broja upita": "Mehr Anfragen erhalten",
  "Online prodaja proizvoda": "Online-Verkauf von Produkten",
  "Online prodaja usluga": "Online-Verkauf von Dienstleistungen",
  "Automatizacija poslovnog procesa": "Geschäftsprozess automatisieren",
  "Rezervacija termina": "Terminbuchung",
  "Upravljanje korisnicima": "Benutzerverwaltung",
  "Edukacija korisnika": "Benutzerschulung",
  "Kreiranje zajednice / community sistema": "Community-System erstellen",
  "Interni poslovni sistem": "Internes Geschäftssystem",
  "SaaS aplikacija": "SaaS-Anwendung",
  "Marketplace/platforma": "Marketplace/Plattform",
  "Bolji SEO i Google vidljivost": "Bessere SEO- und Google-Sichtbarkeit",
  "Bolji dizajn i korisničko iskustvo": "Besseres Design und Nutzererlebnis",
  "U izradi je": "Ist in Entwicklung",
  "Zastarjeli dizajn": "Veraltetes Design",
  "Spor sajt": "Langsame Website",
  "Loša mobilna verzija": "Schlechte mobile Version",
  "Loša Google vidljivost": "Schlechte Google-Sichtbarkeit",
  "Teško uređivanje sadržaja": "Inhalte schwer bearbeitbar",
  "Nema admin panel": "Kein Admin-Panel",
  "Nema online plaćanje": "Keine Online-Zahlung",
  "Loše korisničko iskustvo": "Schlechtes Nutzererlebnis",
  "Nedostaju funkcionalnosti": "Funktionen fehlen",
  "Tehnički problemi": "Technische Probleme",
  "Sigurnosni problemi": "Sicherheitsprobleme",
  "Da, imam domen": "Ja, ich habe eine Domain",
  "Ne, nemam domen": "Nein, ich habe keine Domain",
  "Ne znam šta je domen": "Ich weiß nicht, was eine Domain ist",
  "Da, imam hosting/server": "Ja, ich habe Hosting/Server",
  "Ne, nemam hosting/server": "Nein, ich habe kein Hosting/Server",
  "Ne znam šta je hosting": "Ich weiß nicht, was Hosting ist",
  "Želim prvo više informacija": "Ich möchte zuerst mehr Informationen",
  Početna: "Startseite",
  "O nama": "Über uns",
  Usluge: "Leistungen",
  "Pojedinačne stranice usluga": "Einzelne Leistungsseiten",
  "Portfolio / reference": "Portfolio / Referenzen",
  Tim: "Team",
  Galerija: "Galerie",
  "Blog / novosti": "Blog / Neuigkeiten",
  Cjenovnik: "Preisliste",
  "Česta pitanja": "Häufige Fragen",
  Kontakt: "Kontakt",
  Karijere: "Karriere",
  "Lokacije / poslovnice": "Standorte / Filialen",
  "Pravne stranice": "Rechtliche Seiten",
  "Da, imamo tekstove i slike": "Ja, wir haben Texte und Bilder",
  "Imamo tekstove, ali ne i slike": "Wir haben Texte, aber keine Bilder",
  "Imamo slike, ali ne i tekstove": "Wir haben Bilder, aber keine Texte",
  "Imamo djelimičan sadržaj": "Wir haben teilweise Inhalte",
  "Nemamo sadržaj": "Wir haben keine Inhalte",
  "Treba nam kompletna pomoć oko sadržaja": "Wir brauchen vollständige Hilfe bei Inhalten",
  "Kontakt forma": "Kontaktformular",
  "Forma za upit/ponudu": "Anfrage-/Angebotsformular",
  "Google mapa": "Google-Karte",
  "Blog sistem": "Blog-System",
  "Prikaz referenci": "Referenzanzeige",
  "Newsletter prijava": "Newsletter-Anmeldung",
  "WhatsApp/Viber kontakt dugme": "WhatsApp/Viber-Kontaktbutton",
  Višejezičnost: "Mehrsprachigkeit",
  "Admin panel za uređivanje sadržaja": "Admin-Panel zur Inhaltsbearbeitung",
  "Osnovna SEO optimizacija": "Grundlegende SEO-Optimierung",
  "Napredna SEO struktura": "Erweiterte SEO-Struktur",
  "Ne, samo jedan jezik": "Nein, nur eine Sprache",
  Engleski: "Englisch",
  Njemački: "Deutsch",
  Italijanski: "Italienisch",
  "Ne znam još": "Ich weiß es noch nicht",
  "Plaćanje pouzećem": "Zahlung per Nachnahme",
  "Bankovna uplata": "Banküberweisung",
  "Kartično plaćanje": "Kartenzahlung",
  "Kripto plaćanje": "Krypto-Zahlung",
  "Kurirska služba": "Kurierdienst",
  "Vlastita dostava": "Eigene Lieferung",
  "Lično preuzimanje": "Abholung",
  "Digitalni proizvodi": "Digitale Produkte",
  "Dostava nije potrebna": "Lieferung nicht erforderlich",
  "Ručno kroz admin panel": "Manuell über Admin-Panel",
  "Import iz Excel/CSV fajla": "Import aus Excel/CSV",
  "API integracija sa drugim sistemom": "API-Integration mit anderem System",
  "Automatska sinhronizacija sa dobavljačem": "Automatische Lieferantensynchronisierung",
  "Registrovani korisnici": "Registrierte Benutzer",
  Kupci: "Kunden",
  Zaposleni: "Mitarbeiter",
  Partneri: "Partner",
  "Edukatori / mentori": "Trainer / Mentoren",
  Moderatori: "Moderatoren",
  Menadžeri: "Manager",
  Klijenti: "Klienten",
  Registracija: "Registrierung",
  "Zaboravljena lozinka": "Passwort vergessen",
  "Profil korisnika": "Benutzerprofil",
  Dashboard: "Dashboard",
  Notifikacije: "Benachrichtigungen",
  "Historija aktivnosti": "Aktivitätshistorie",
  Plaćanja: "Zahlungen",
  "Dokumenti/fajlovi": "Dokumente/Dateien",
  Poruke: "Nachrichten",
  "Postavke naloga": "Kontoeinstellungen",
  "Korisnički dashboard": "Benutzer-Dashboard",
  "Uloge i permisije": "Rollen und Berechtigungen",
  "Upload fajlova": "Dateiupload",
  Komentari: "Kommentare",
  "Chat / messaging": "Chat / Messaging",
  "Email notifikacije": "Email-Benachrichtigungen",
  "Push notifikacije": "Push-Benachrichtigungen",
  Kalendar: "Kalender",
  Rezervacije: "Buchungen",
  "Online plaćanje": "Online-Zahlung",
  "Pretplate / subscription": "Abonnements",
  Fakture: "Rechnungen",
  Izvještaji: "Berichte",
  Statistika: "Statistik",
  API: "API",
  "Integracije sa drugim sistemima": "Integrationen mit anderen Systemen",
  "Mobilna aplikacija kasnije": "Mobile App später",
  Termine: "Termine",
  Konsultacije: "Beratungen",
  Vozila: "Fahrzeuge",
  Smještaj: "Unterkunft",
  Stolove: "Tische",
  Prostorije: "Räume",
  "Oprema/resurse": "Ausrüstung/Ressourcen",
  Opcionalno: "Optional",
  "Email podsjetnik": "Email-Erinnerung",
  "SMS podsjetnik": "SMS-Erinnerung",
  "WhatsApp/Viber podsjetnik": "WhatsApp/Viber-Erinnerung",
  "Podsjetnik u aplikaciji": "In-App-Erinnerung",
  Uslugu: "Dienstleistung",
  Proizvod: "Produkt",
  Edukaciju: "Schulung",
  Event: "Event",
  "Akciju/popust": "Aktion/Rabatt",
  "Prijavu na listu čekanja": "Wartelistenanmeldung",
  "Preuzimanje dokumenta": "Dokument-Download",
  "Poslati upit": "Anfrage senden",
  "Kupiti proizvod": "Produkt kaufen",
  "Zakazati termin": "Termin buchen",
  "Prijaviti se": "Anmelden",
  Nazvati: "Anrufen",
  "Poslati poruku": "Nachricht senden",
  "Preuzeti dokument": "Dokument herunterladen",
  "Ostaviti email": "Email hinterlassen",
  "Email kampanja": "Email-Kampagne",
  Dizajn: "Design",
  Brzinu: "Geschwindigkeit",
  "Mobilnu verziju": "Mobile Version",
  SEO: "SEO",
  "Strukturu sadržaja": "Inhaltsstruktur",
  Sigurnost: "Sicherheit",
  "Tehničku platformu": "Technische Plattform",
  Konverzije: "Konversionen",
  "Da, sav sadržaj": "Ja, alle Inhalte",
  "Da, djelimično": "Ja, teilweise",
  "Ne, želimo novi sadržaj": "Nein, wir möchten neue Inhalte",
  Možda: "Vielleicht",
  Stranice: "Seiten",
  "Blog objave": "Blogbeiträge",
  Proizvodi: "Produkte",
  Korisnici: "Benutzer",
  Narudžbe: "Bestellungen",
  Slike: "Bilder",
  Dokumenti: "Dokumente",
  "SEO meta podaci": "SEO-Metadaten",
  Logo: "Logo",
  Boje: "Farben",
  Fontove: "Schriften",
  "Brand guide": "Brand Guide",
  Fotografije: "Fotos",
  "Video materijale": "Videomaterial",
  "Nemamo vizuelni identitet": "Wir haben keine visuelle Identität",
  "Treba nam pomoć oko brendinga": "Wir brauchen Hilfe beim Branding",
  "Moderan i minimalistički": "Modern und minimalistisch",
  "Premium/luksuzan": "Premium/luxuriös",
  Korporativan: "Korporativ",
  "Kreativan i dinamičan": "Kreativ und dynamisch",
  "Tech/startup": "Tech/Startup",
  "Medicinski/profesionalan": "Medizinisch/professionell",
  "Topao i prijateljski": "Warm und freundlich",
  "Elegantno i jednostavno": "Elegant und einfach",
  "Ne znam, želim prijedlog": "Ich weiß nicht, ich möchte einen Vorschlag",
  "Veoma važno": "Sehr wichtig",
  "Važno, ali osnovno": "Wichtig, aber grundlegend",
  "Nije trenutno prioritet": "Derzeit keine Priorität",
  "Ne znam šta je SEO": "Ich weiß nicht, was SEO ist",
  "Želim preporuku": "Ich möchte eine Empfehlung",
  "Mi pripremamo sav sadržaj": "Wir bereiten alle Inhalte vor",
  "Vi pripremate sadržaj": "Sie bereiten Inhalte vor",
  "Zajedno pripremamo sadržaj": "Wir bereiten Inhalte gemeinsam vor",
  "Nemamo još definisano": "Noch nicht definiert",
  "Treba nam kompletna pomoć": "Wir brauchen vollständige Hilfe",
  Djelimično: "Teilweise",
  Tekstove: "Texte",
  Cijene: "Preise",
  Kategorije: "Kategorien",
  "Uslovi korištenja": "Nutzungsbedingungen",
  "Politika privatnosti": "Datenschutzerklärung",
  "Cookie politika": "Cookie-Richtlinie",
  "GDPR saglasnosti": "DSGVO-Einwilligungen",
  "Pravila povrata/reklamacije": "Rückgabe-/Reklamationsregeln",
  "Uslovi kupovine": "Kaufbedingungen",
  "Do 500 €": "Bis 500 €",
  "Želim prvo okvirnu procjenu": "Ich möchte zuerst eine grobe Einschätzung",
  "Ne želim navesti budžet": "Ich möchte kein Budget angeben",
  Odmah: "Sofort",
  "U narednih 30 dana": "In den nächsten 30 Tagen",
  "U naredna 2-3 mjeseca": "In den nächsten 2-3 Monaten",
  Kasnije: "Später",
  "Poželjno, ali nije strogo": "Wünschenswert, aber nicht strikt",
  Cijena: "Preis",
  "Brzina izrade": "Umsetzungsgeschwindigkeit",
  "Kvalitet dizajna": "Designqualität",
  Performanse: "Performance",
  "Fleksibilnost sistema": "Systemflexibilität",
  "Dugoročna skalabilnost": "Langfristige Skalierbarkeit",
  "Jednostavno održavanje": "Einfache Wartung",
  "Želim okvirnu ponudu": "Ich möchte ein grobes Angebot",
  "Želim konsultacije": "Ich möchte Beratung",
  "Želim tehnički prijedlog": "Ich möchte einen technischen Vorschlag",
  "Želim prvo da analizirate moje odgovore": "Ich möchte zuerst eine Analyse meiner Antworten",
};

optionText.it = {
  ...optionText.en,
  Da: "Sì",
  Ne: "No",
  "Nisam siguran/sigurna": "Non sono sicuro/a",
  "Možda kasnije": "Forse più tardi",
  "Ne znam": "Non lo so",
  Drugo: "Altro",
  yes: "Sì",
  no: "No",
  not_sure: "Non sono sicuro/a",
  "Prezentacioni web sajt": "Sito web di presentazione",
  "Web shop / online prodavnica": "Shop online",
  "Web aplikacija / platforma": "Applicazione web / piattaforma",
  "Booking / rezervacijski sistem": "Sistema booking / prenotazioni",
  "Redizajn postojećeg sajta ili aplikacije": "Redesign di sito o applicazione esistente",
  "Predstavljanje firme ili usluga": "Presentare azienda o servizi",
  "Povećanje broja upita": "Aumentare il numero di richieste",
  "Online prodaja proizvoda": "Vendita online di prodotti",
  "Online prodaja usluga": "Vendita online di servizi",
  "Automatizacija poslovnog procesa": "Automatizzare un processo aziendale",
  "Rezervacija termina": "Prenotazione appuntamenti",
  "Upravljanje korisnicima": "Gestione utenti",
  "Edukacija korisnika": "Educazione utenti",
  "Kreiranje zajednice / community sistema": "Creazione community",
  "Interni poslovni sistem": "Sistema aziendale interno",
  "SaaS aplikacija": "Applicazione SaaS",
  "Marketplace/platforma": "Marketplace/piattaforma",
  "Bolji SEO i Google vidljivost": "Migliore SEO e visibilità Google",
  "Bolji dizajn i korisničko iskustvo": "Miglior design ed esperienza utente",
  "U izradi je": "È in sviluppo",
  "Zastarjeli dizajn": "Design obsoleto",
  "Spor sajt": "Sito lento",
  "Loša mobilna verzija": "Versione mobile debole",
  "Loša Google vidljivost": "Scarsa visibilità Google",
  "Teško uređivanje sadržaja": "Contenuti difficili da modificare",
  "Nema admin panel": "Nessun pannello admin",
  "Nema online plaćanje": "Nessun pagamento online",
  "Loše korisničko iskustvo": "Esperienza utente debole",
  "Nedostaju funkcionalnosti": "Funzionalità mancanti",
  "Tehnički problemi": "Problemi tecnici",
  "Sigurnosni problemi": "Problemi di sicurezza",
  "Da, imam domen": "Sì, ho un dominio",
  "Ne, nemam domen": "No, non ho un dominio",
  "Ne znam šta je domen": "Non so cos'è un dominio",
  "Da, imam hosting/server": "Sì, ho hosting/server",
  "Ne, nemam hosting/server": "No, non ho hosting/server",
  "Ne znam šta je hosting": "Non so cos'è l'hosting",
  "Želim prvo više informacija": "Voglio prima più informazioni",
  Početna: "Home",
  "O nama": "Chi siamo",
  Usluge: "Servizi",
  "Pojedinačne stranice usluga": "Pagine singole dei servizi",
  "Portfolio / reference": "Portfolio / referenze",
  Tim: "Team",
  Galerija: "Galleria",
  "Blog / novosti": "Blog / notizie",
  Cjenovnik: "Listino prezzi",
  "Česta pitanja": "FAQ",
  Kontakt: "Contatto",
  Karijere: "Carriere",
  "Lokacije / poslovnice": "Sedi / filiali",
  "Pravne stranice": "Pagine legali",
  "Da, imamo tekstove i slike": "Sì, abbiamo testi e immagini",
  "Imamo tekstove, ali ne i slike": "Abbiamo testi, ma non immagini",
  "Imamo slike, ali ne i tekstove": "Abbiamo immagini, ma non testi",
  "Imamo djelimičan sadržaj": "Abbiamo contenuti parziali",
  "Nemamo sadržaj": "Non abbiamo contenuti",
  "Treba nam kompletna pomoć oko sadržaja": "Ci serve supporto completo sui contenuti",
  "Kontakt forma": "Modulo contatto",
  "Forma za upit/ponudu": "Modulo richiesta/preventivo",
  "Google mapa": "Mappa Google",
  "Blog sistem": "Sistema blog",
  "Prikaz referenci": "Visualizzazione referenze",
  "Newsletter prijava": "Iscrizione newsletter",
  "WhatsApp/Viber kontakt dugme": "Pulsante contatto WhatsApp/Viber",
  Višejezičnost: "Multilingua",
  "Admin panel za uređivanje sadržaja": "Pannello admin per contenuti",
  "Osnovna SEO optimizacija": "SEO base",
  "Napredna SEO struktura": "Struttura SEO avanzata",
  "Ne, samo jedan jezik": "No, una sola lingua",
  Engleski: "Inglese",
  Njemački: "Tedesco",
  Italijanski: "Italiano",
  "Ne znam još": "Non lo so ancora",
  "Plaćanje pouzećem": "Pagamento alla consegna",
  "Bankovna uplata": "Bonifico bancario",
  "Kartično plaćanje": "Pagamento con carta",
  "Kripto plaćanje": "Pagamento crypto",
  "Kurirska služba": "Corriere",
  "Vlastita dostava": "Consegna propria",
  "Lično preuzimanje": "Ritiro personale",
  "Digitalni proizvodi": "Prodotti digitali",
  "Dostava nije potrebna": "Consegna non necessaria",
  "Ručno kroz admin panel": "Manuale tramite admin panel",
  "Import iz Excel/CSV fajla": "Import da Excel/CSV",
  "API integracija sa drugim sistemom": "Integrazione API con altro sistema",
  "Automatska sinhronizacija sa dobavljačem": "Sincronizzazione automatica con fornitore",
  "Registrovani korisnici": "Utenti registrati",
  Kupci: "Clienti",
  Zaposleni: "Dipendenti",
  Partneri: "Partner",
  "Edukatori / mentori": "Educatori / mentori",
  Moderatori: "Moderatori",
  Menadžeri: "Manager",
  Klijenti: "Clienti",
  Registracija: "Registrazione",
  "Zaboravljena lozinka": "Password dimenticata",
  "Profil korisnika": "Profilo utente",
  Dashboard: "Dashboard",
  Notifikacije: "Notifiche",
  "Historija aktivnosti": "Storico attività",
  Plaćanja: "Pagamenti",
  "Dokumenti/fajlovi": "Documenti/file",
  Poruke: "Messaggi",
  "Postavke naloga": "Impostazioni account",
  "Korisnički dashboard": "Dashboard utente",
  "Uloge i permisije": "Ruoli e permessi",
  "Upload fajlova": "Upload file",
  Komentari: "Commenti",
  "Chat / messaging": "Chat / messaggi",
  "Email notifikacije": "Notifiche email",
  "Push notifikacije": "Notifiche push",
  Kalendar: "Calendario",
  Rezervacije: "Prenotazioni",
  "Online plaćanje": "Pagamento online",
  "Pretplate / subscription": "Abbonamenti",
  Fakture: "Fatture",
  Izvještaji: "Report",
  Statistika: "Statistiche",
  API: "API",
  "Integracije sa drugim sistemima": "Integrazioni con altri sistemi",
  "Mobilna aplikacija kasnije": "App mobile più avanti",
  Termine: "Appuntamenti",
  Konsultacije: "Consulenze",
  Vozila: "Veicoli",
  Smještaj: "Alloggio",
  Stolove: "Tavoli",
  Prostorije: "Sale/spazi",
  "Oprema/resurse": "Attrezzature/risorse",
  Opcionalno: "Opzionale",
  "Email podsjetnik": "Promemoria email",
  "SMS podsjetnik": "Promemoria SMS",
  "WhatsApp/Viber podsjetnik": "Promemoria WhatsApp/Viber",
  "Podsjetnik u aplikaciji": "Promemoria nell'app",
  Uslugu: "Servizio",
  Proizvod: "Prodotto",
  Edukaciju: "Formazione",
  Event: "Evento",
  "Akciju/popust": "Promozione/sconto",
  "Prijavu na listu čekanja": "Iscrizione lista d'attesa",
  "Preuzimanje dokumenta": "Download documento",
  "Poslati upit": "Inviare richiesta",
  "Kupiti proizvod": "Acquistare prodotto",
  "Zakazati termin": "Prenotare appuntamento",
  "Prijaviti se": "Iscriversi",
  Nazvati: "Chiamare",
  "Poslati poruku": "Inviare messaggio",
  "Preuzeti dokument": "Scaricare documento",
  "Ostaviti email": "Lasciare email",
  "Email kampanja": "Campagna email",
  Dizajn: "Design",
  Brzinu: "Velocità",
  "Mobilnu verziju": "Versione mobile",
  SEO: "SEO",
  "Strukturu sadržaja": "Struttura contenuti",
  Sigurnost: "Sicurezza",
  "Tehničku platformu": "Piattaforma tecnica",
  Konverzije: "Conversioni",
  "Da, sav sadržaj": "Sì, tutti i contenuti",
  "Da, djelimično": "Sì, parzialmente",
  "Ne, želimo novi sadržaj": "No, vogliamo nuovi contenuti",
  Možda: "Forse",
  Stranice: "Pagine",
  "Blog objave": "Articoli blog",
  Proizvodi: "Prodotti",
  Korisnici: "Utenti",
  Narudžbe: "Ordini",
  Slike: "Immagini",
  Dokumenti: "Documenti",
  "SEO meta podaci": "Meta dati SEO",
  Logo: "Logo",
  Boje: "Colori",
  Fontove: "Font",
  "Brand guide": "Brand guide",
  Fotografije: "Fotografie",
  "Video materijale": "Materiali video",
  "Nemamo vizuelni identitet": "Non abbiamo identità visiva",
  "Treba nam pomoć oko brendinga": "Ci serve aiuto sul branding",
  "Moderan i minimalistički": "Moderno e minimalista",
  "Premium/luksuzan": "Premium/lusso",
  Korporativan: "Corporate",
  "Kreativan i dinamičan": "Creativo e dinamico",
  "Tech/startup": "Tech/startup",
  "Medicinski/profesionalan": "Medico/professionale",
  "Topao i prijateljski": "Caldo e amichevole",
  "Elegantno i jednostavno": "Elegante e semplice",
  "Ne znam, želim prijedlog": "Non lo so, voglio una proposta",
  "Veoma važno": "Molto importante",
  "Važno, ali osnovno": "Importante, ma base",
  "Nije trenutno prioritet": "Non è una priorità ora",
  "Ne znam šta je SEO": "Non so cos'è la SEO",
  "Želim preporuku": "Voglio una raccomandazione",
  "Mi pripremamo sav sadržaj": "Prepariamo noi tutti i contenuti",
  "Vi pripremate sadržaj": "Preparate voi i contenuti",
  "Zajedno pripremamo sadržaj": "Prepariamo insieme i contenuti",
  "Nemamo još definisano": "Non ancora definito",
  "Treba nam kompletna pomoć": "Ci serve supporto completo",
  Djelimično: "Parzialmente",
  Tekstove: "Testi",
  Cijene: "Prezzi",
  Kategorije: "Categorie",
  "Uslovi korištenja": "Termini di utilizzo",
  "Politika privatnosti": "Privacy policy",
  "Cookie politika": "Cookie policy",
  "GDPR saglasnosti": "Consensi GDPR",
  "Pravila povrata/reklamacije": "Regole resi/reclami",
  "Uslovi kupovine": "Termini di acquisto",
  "Do 500 €": "Fino a 500 €",
  "Želim prvo okvirnu procjenu": "Voglio prima una stima indicativa",
  "Ne želim navesti budžet": "Non voglio indicare budget",
  Odmah: "Subito",
  "U narednih 30 dana": "Nei prossimi 30 giorni",
  "U naredna 2-3 mjeseca": "Nei prossimi 2-3 mesi",
  Kasnije: "Più tardi",
  "Poželjno, ali nije strogo": "Preferibile, ma non rigido",
  Cijena: "Prezzo",
  "Brzina izrade": "Velocità di realizzazione",
  "Kvalitet dizajna": "Qualità design",
  Performanse: "Performance",
  "Fleksibilnost sistema": "Flessibilità del sistema",
  "Dugoročna skalabilnost": "Scalabilità a lungo termine",
  "Jednostavno održavanje": "Manutenzione semplice",
  "Želim okvirnu ponudu": "Voglio un'offerta indicativa",
  "Želim konsultacije": "Voglio una consulenza",
  "Želim tehnički prijedlog": "Voglio una proposta tecnica",
  "Želim prvo da analizirate moje odgovore": "Voglio prima l'analisi delle mie risposte",
};

const localizeOption = (option: InquiryOption, language: Language): InquiryOption => {
  if (language === "sr") return option;

  return {
    ...option,
    label: optionText[language][option.value] || optionText[language][option.label] || option.label,
  };
};

const localizeField = (field: InquiryField, language: Language): InquiryField => {
  if (language === "sr") return field;
  const text = fieldText[language][field.key];

  return {
    ...field,
    label: text?.label || field.label,
    description: text?.description || field.description,
    placeholder: text?.placeholder || field.placeholder,
    options: field.options?.map((option) => localizeOption(option, language)),
  };
};

export const getProjectInquirySteps = (language: Language = "sr") =>
  projectInquirySteps.map((step) => {
    if (language === "sr") return step;
    const text = stepText[language][step.key];

    return {
      ...step,
      eyebrow: text?.eyebrow || step.eyebrow,
      title: text?.title || step.title,
      description: text?.description || step.description,
      fields: step.fields.map((field) => localizeField(field, language)),
    };
  });

export const getVisibleSteps = (answers: InquiryAnswers, steps: InquiryStep[] = projectInquirySteps) =>
  steps.filter((step) => {
    if (!step.projectTypes?.length) return true;
    return step.projectTypes.includes(String(answers.project_type || ""));
  });

export const getVisibleFields = (step: InquiryStep, answers: InquiryAnswers) =>
  step.fields.filter((field) => !field.showWhen || field.showWhen(answers));

export const getAllVisibleFields = (answers: InquiryAnswers, steps: InquiryStep[] = projectInquirySteps) =>
  getVisibleSteps(answers, steps).flatMap((step) => getVisibleFields(step, answers));

export const getFieldLabel = (key: string) =>
  projectInquirySteps.flatMap((step) => step.fields).find((field) => field.key === key)?.label || key;

export const calculateComplexityScore = (answers: InquiryAnswers) => {
  let score = 0;
  const projectType = String(answers.project_type || "");
  const addForArray = (key: string, weight = 1) => {
    const value = answers[key];
    if (Array.isArray(value)) score += value.length * weight;
  };

  if (projectType === "landing_page") score += 1;
  if (projectType === "presentation_website") score += 2;
  if (projectType === "booking_system") score += 5;
  if (projectType === "ecommerce") score += 7;
  if (projectType === "web_application") score += 10;
  if (projectType === "redesign") score += 4;

  addForArray("main_goals");
  addForArray("website_features", 2);
  addForArray("website_languages", 2);
  addForArray("payment_methods", 2);
  addForArray("delivery_methods");
  addForArray("app_users", 2);
  addForArray("account_features", 2);
  addForArray("app_features", 2);
  addForArray("analytics_tools");

  if (answers.user_accounts === "yes") score += 3;
  if (String(answers.product_count || "").includes("500")) score += 4;
  if (String(answers.product_count || "").includes("2000")) score += 8;
  if (answers.booking_payment === "Da") score += 2;
  if (answers.data_migration === "Da") score += 3;

  if (score >= 28) return "enterprise";
  if (score >= 16) return "high";
  if (score >= 8) return "medium";
  return "low";
};

export const calculateBudgetScore = (budgetRange: InquiryValue) => {
  const value = String(budgetRange || "");
  if (!value || value.includes("procjenu") || value.includes("Ne želim")) return "unknown";
  if (value.includes("Do 500")) return "low_budget";
  if (value.includes("500-1.500") || value.includes("1.500-3.000")) return "standard";
  if (value.includes("3.000-7.000") || value.includes("7.000-15.000")) return "serious";
  if (value.includes("15.000")) return "enterprise";
  return "unknown";
};
